// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invites.sql

package pgdbsql

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createInvite = `-- name: CreateInvite :one
INSERT INTO invites (
    id,
    agglomeration_id,
    expires_at
) VALUES (
    $1::uuid,
    $2::uuid,
    $3::timestamptz
)
RETURNING id, agglomeration_id, status, expires_at, created_at
`

type CreateInviteParams struct {
	ID              uuid.UUID
	AgglomerationID uuid.UUID
	ExpiresAt       time.Time
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error) {
	row := q.db.QueryRowContext(ctx, createInvite, arg.ID, arg.AgglomerationID, arg.ExpiresAt)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.AgglomerationID,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteInvite = `-- name: DeleteInvite :exec
DELETE FROM invites
WHERE id = $1::uuid
`

func (q *Queries) DeleteInvite(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteInvite, id)
	return err
}

const getInviteByID = `-- name: GetInviteByID :one
SELECT id, agglomeration_id, status, expires_at, created_at
FROM invites
WHERE id = $1::uuid
`

func (q *Queries) GetInviteByID(ctx context.Context, id uuid.UUID) (Invite, error) {
	row := q.db.QueryRowContext(ctx, getInviteByID, id)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.AgglomerationID,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateInviteStatus = `-- name: UpdateInviteStatus :one
UPDATE invites
SET
    status = $1::invite_status
WHERE id = $2::uuid
RETURNING id, agglomeration_id, status, expires_at, created_at
`

type UpdateInviteStatusParams struct {
	Status InviteStatus
	ID     uuid.UUID
}

func (q *Queries) UpdateInviteStatus(ctx context.Context, arg UpdateInviteStatusParams) (Invite, error) {
	row := q.db.QueryRowContext(ctx, updateInviteStatus, arg.Status, arg.ID)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.AgglomerationID,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
