// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: member_roles.sql

package pgdbsql

import (
	"context"

	"github.com/google/uuid"
)

const createMemberRole = `-- name: CreateMemberRole :exec
INSERT INTO member_roles (
    member_id,
    role_id
) VALUES (
    $1::uuid,
    $2::uuid
)
ON CONFLICT DO NOTHING
`

type CreateMemberRoleParams struct {
	MemberID uuid.UUID
	RoleID   uuid.UUID
}

func (q *Queries) CreateMemberRole(ctx context.Context, arg CreateMemberRoleParams) error {
	_, err := q.db.ExecContext(ctx, createMemberRole, arg.MemberID, arg.RoleID)
	return err
}

const deleteMemberRole = `-- name: DeleteMemberRole :exec
DELETE FROM member_roles
WHERE member_id = $1::uuid
  AND role_id = $2::uuid
`

type DeleteMemberRoleParams struct {
	MemberID uuid.UUID
	RoleID   uuid.UUID
}

func (q *Queries) DeleteMemberRole(ctx context.Context, arg DeleteMemberRoleParams) error {
	_, err := q.db.ExecContext(ctx, deleteMemberRole, arg.MemberID, arg.RoleID)
	return err
}

const listMemberRoles = `-- name: ListMemberRoles :many
SELECT member_id, role_id
FROM member_roles
WHERE member_id = $1::uuid
`

func (q *Queries) ListMemberRoles(ctx context.Context, memberID uuid.UUID) ([]MemberRole, error) {
	rows, err := q.db.QueryContext(ctx, listMemberRoles, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemberRole
	for rows.Next() {
		var i MemberRole
		if err := rows.Scan(&i.MemberID, &i.RoleID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
