// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pgdbsql

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type AdministrationStatus string

const (
	AdministrationStatusActive    AdministrationStatus = "active"
	AdministrationStatusInactive  AdministrationStatus = "inactive"
	AdministrationStatusSuspended AdministrationStatus = "suspended"
)

func (e *AdministrationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AdministrationStatus(s)
	case string:
		*e = AdministrationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AdministrationStatus: %T", src)
	}
	return nil
}

type NullAdministrationStatus struct {
	AdministrationStatus AdministrationStatus
	Valid                bool // Valid is true if AdministrationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAdministrationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AdministrationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AdministrationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAdministrationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AdministrationStatus), nil
}

type CitiesStatus string

const (
	CitiesStatusActive   CitiesStatus = "active"
	CitiesStatusInactive CitiesStatus = "inactive"
	CitiesStatusArchived CitiesStatus = "archived"
)

func (e *CitiesStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CitiesStatus(s)
	case string:
		*e = CitiesStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CitiesStatus: %T", src)
	}
	return nil
}

type NullCitiesStatus struct {
	CitiesStatus CitiesStatus
	Valid        bool // Valid is true if CitiesStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCitiesStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CitiesStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CitiesStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCitiesStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CitiesStatus), nil
}

type InboxEventStatus string

const (
	InboxEventStatusPending    InboxEventStatus = "pending"
	InboxEventStatusProcessing InboxEventStatus = "processing"
	InboxEventStatusProcessed  InboxEventStatus = "processed"
	InboxEventStatusFailed     InboxEventStatus = "failed"
)

func (e *InboxEventStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InboxEventStatus(s)
	case string:
		*e = InboxEventStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for InboxEventStatus: %T", src)
	}
	return nil
}

type NullInboxEventStatus struct {
	InboxEventStatus InboxEventStatus
	Valid            bool // Valid is true if InboxEventStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInboxEventStatus) Scan(value interface{}) error {
	if value == nil {
		ns.InboxEventStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InboxEventStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInboxEventStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InboxEventStatus), nil
}

type InviteStatus string

const (
	InviteStatusSent     InviteStatus = "sent"
	InviteStatusDeclined InviteStatus = "declined"
	InviteStatusAccepted InviteStatus = "accepted"
)

func (e *InviteStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InviteStatus(s)
	case string:
		*e = InviteStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for InviteStatus: %T", src)
	}
	return nil
}

type NullInviteStatus struct {
	InviteStatus InviteStatus
	Valid        bool // Valid is true if InviteStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInviteStatus) Scan(value interface{}) error {
	if value == nil {
		ns.InviteStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InviteStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInviteStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InviteStatus), nil
}

type OutboxEventStatus string

const (
	OutboxEventStatusPending    OutboxEventStatus = "pending"
	OutboxEventStatusProcessing OutboxEventStatus = "processing"
	OutboxEventStatusSent       OutboxEventStatus = "sent"
	OutboxEventStatusFailed     OutboxEventStatus = "failed"
)

func (e *OutboxEventStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OutboxEventStatus(s)
	case string:
		*e = OutboxEventStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OutboxEventStatus: %T", src)
	}
	return nil
}

type NullOutboxEventStatus struct {
	OutboxEventStatus OutboxEventStatus
	Valid             bool // Valid is true if OutboxEventStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOutboxEventStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OutboxEventStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OutboxEventStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOutboxEventStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OutboxEventStatus), nil
}

type Agglomeration struct {
	ID        uuid.UUID
	Status    AdministrationStatus
	Name      string
	Icon      sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type City struct {
	ID              uuid.UUID
	AgglomerationID uuid.NullUUID
	Status          CitiesStatus
	Slug            sql.NullString
	Name            string
	Icon            sql.NullString
	Banner          sql.NullString
	Point           []byte
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type InboxEvent struct {
	ID          uuid.UUID
	Topic       string
	Key         string
	Type        string
	Version     int32
	Producer    string
	Payload     json.RawMessage
	Status      InboxEventStatus
	Attempts    int32
	CreatedAt   time.Time
	NextRetryAt sql.NullTime
	ProcessedAt sql.NullTime
}

type Invite struct {
	ID              uuid.UUID
	AgglomerationID uuid.UUID
	Status          InviteStatus
	ExpiresAt       time.Time
	CreatedAt       time.Time
}

type Member struct {
	ID              uuid.UUID
	AccountID       uuid.UUID
	AgglomerationID uuid.UUID
	Position        sql.NullString
	Label           sql.NullString
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type MemberRole struct {
	MemberID uuid.UUID
	RoleID   uuid.UUID
}

type OutboxEvent struct {
	ID          uuid.UUID
	Topic       string
	Key         string
	Type        string
	Version     int32
	Producer    string
	Payload     json.RawMessage
	Status      OutboxEventStatus
	Attempts    int32
	CreatedAt   time.Time
	NextRetryAt sql.NullTime
	SentAt      sql.NullTime
}

type Permission struct {
	ID          uuid.UUID
	Code        string
	Description string
}

type Profile struct {
	AccountID uuid.UUID
	Username  string
	Official  bool
	Pseudonym sql.NullString
	UpdatedAt time.Time
	CreatedAt time.Time
}

type Role struct {
	ID              uuid.UUID
	AgglomerationID uuid.UUID
	Head            bool
	Editable        bool
	Rank            int32
	Name            string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type RolePermission struct {
	RoleID       uuid.UUID
	PermissionID uuid.UUID
}
