services:
  organizations-svc:
    build: .
    container_name: organizations-svc
    environment:
      - KV_VIPER_FILE=./config_docker.yaml
    ports:
      - "8003:8000"
    networks:
      - netbill-net

  organizations-svc-postgres:
    image: postgis/postgis:16-3.4
    container_name: organizations-svc-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "7003:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - netbill-net

  organizations-svc-swagger:
    image: swaggerapi/swagger-ui
    container_name: organizations-svc-swagger
    environment:
      - SWAGGER_JSON=/docs/api-bundled.yaml
    volumes:
      - ./docs:/docs:ro
    ports:
      - "5003:8080"
    networks:
      - netbill-net

volumes:
  pgdata:
  bundle:

networks:
  netbill-net:
    external: true
