/*
organizations-svc API

API documentation for organizations-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// checks if the UpdateRolePermissionsDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateRolePermissionsDataAttributes{}

// UpdateRolePermissionsDataAttributes struct for UpdateRolePermissionsDataAttributes
type UpdateRolePermissionsDataAttributes struct {
	// An ordered list of role IDs representing the new roles hierarchy
	Permissions []UpdateRolePermissionsDataAttributesPermissionsInner `json:"permissions,omitempty"`
}

// NewUpdateRolePermissionsDataAttributes instantiates a new UpdateRolePermissionsDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateRolePermissionsDataAttributes() *UpdateRolePermissionsDataAttributes {
	this := UpdateRolePermissionsDataAttributes{}
	return &this
}

// NewUpdateRolePermissionsDataAttributesWithDefaults instantiates a new UpdateRolePermissionsDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateRolePermissionsDataAttributesWithDefaults() *UpdateRolePermissionsDataAttributes {
	this := UpdateRolePermissionsDataAttributes{}
	return &this
}

// GetPermissions returns the Permissions field value if set, zero value otherwise.
func (o *UpdateRolePermissionsDataAttributes) GetPermissions() []UpdateRolePermissionsDataAttributesPermissionsInner {
	if o == nil || IsNil(o.Permissions) {
		var ret []UpdateRolePermissionsDataAttributesPermissionsInner
		return ret
	}
	return o.Permissions
}

// GetPermissionsOk returns a tuple with the Permissions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateRolePermissionsDataAttributes) GetPermissionsOk() ([]UpdateRolePermissionsDataAttributesPermissionsInner, bool) {
	if o == nil || IsNil(o.Permissions) {
		return nil, false
	}
	return o.Permissions, true
}

// HasPermissions returns a boolean if a field has been set.
func (o *UpdateRolePermissionsDataAttributes) HasPermissions() bool {
	if o != nil && !IsNil(o.Permissions) {
		return true
	}

	return false
}

// SetPermissions gets a reference to the given []UpdateRolePermissionsDataAttributesPermissionsInner and assigns it to the Permissions field.
func (o *UpdateRolePermissionsDataAttributes) SetPermissions(v []UpdateRolePermissionsDataAttributesPermissionsInner) {
	o.Permissions = v
}

func (o UpdateRolePermissionsDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateRolePermissionsDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Permissions) {
		toSerialize["permissions"] = o.Permissions
	}
	return toSerialize, nil
}

type NullableUpdateRolePermissionsDataAttributes struct {
	value *UpdateRolePermissionsDataAttributes
	isSet bool
}

func (v NullableUpdateRolePermissionsDataAttributes) Get() *UpdateRolePermissionsDataAttributes {
	return v.value
}

func (v *NullableUpdateRolePermissionsDataAttributes) Set(val *UpdateRolePermissionsDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateRolePermissionsDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateRolePermissionsDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateRolePermissionsDataAttributes(val *UpdateRolePermissionsDataAttributes) *NullableUpdateRolePermissionsDataAttributes {
	return &NullableUpdateRolePermissionsDataAttributes{value: val, isSet: true}
}

func (v NullableUpdateRolePermissionsDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateRolePermissionsDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


