/*
NetBill organizations-svc API

API documentation for organizations-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateOrganizationDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateOrganizationDataAttributes{}

// UpdateOrganizationDataAttributes struct for UpdateOrganizationDataAttributes
type UpdateOrganizationDataAttributes struct {
	// The name of the organization
	Name string `json:"name"`
	// The media key for the organization's icon
	IconKey *string `json:"icon_key,omitempty"`
	// The media key for the organization's banner
	BannerKey *string `json:"banner_key,omitempty"`
}

type _UpdateOrganizationDataAttributes UpdateOrganizationDataAttributes

// NewUpdateOrganizationDataAttributes instantiates a new UpdateOrganizationDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateOrganizationDataAttributes(name string) *UpdateOrganizationDataAttributes {
	this := UpdateOrganizationDataAttributes{}
	this.Name = name
	return &this
}

// NewUpdateOrganizationDataAttributesWithDefaults instantiates a new UpdateOrganizationDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateOrganizationDataAttributesWithDefaults() *UpdateOrganizationDataAttributes {
	this := UpdateOrganizationDataAttributes{}
	return &this
}

// GetName returns the Name field value
func (o *UpdateOrganizationDataAttributes) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *UpdateOrganizationDataAttributes) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *UpdateOrganizationDataAttributes) SetName(v string) {
	o.Name = v
}

// GetIconKey returns the IconKey field value if set, zero value otherwise.
func (o *UpdateOrganizationDataAttributes) GetIconKey() string {
	if o == nil || IsNil(o.IconKey) {
		var ret string
		return ret
	}
	return *o.IconKey
}

// GetIconKeyOk returns a tuple with the IconKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOrganizationDataAttributes) GetIconKeyOk() (*string, bool) {
	if o == nil || IsNil(o.IconKey) {
		return nil, false
	}
	return o.IconKey, true
}

// HasIconKey returns a boolean if a field has been set.
func (o *UpdateOrganizationDataAttributes) HasIconKey() bool {
	if o != nil && !IsNil(o.IconKey) {
		return true
	}

	return false
}

// SetIconKey gets a reference to the given string and assigns it to the IconKey field.
func (o *UpdateOrganizationDataAttributes) SetIconKey(v string) {
	o.IconKey = &v
}

// GetBannerKey returns the BannerKey field value if set, zero value otherwise.
func (o *UpdateOrganizationDataAttributes) GetBannerKey() string {
	if o == nil || IsNil(o.BannerKey) {
		var ret string
		return ret
	}
	return *o.BannerKey
}

// GetBannerKeyOk returns a tuple with the BannerKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOrganizationDataAttributes) GetBannerKeyOk() (*string, bool) {
	if o == nil || IsNil(o.BannerKey) {
		return nil, false
	}
	return o.BannerKey, true
}

// HasBannerKey returns a boolean if a field has been set.
func (o *UpdateOrganizationDataAttributes) HasBannerKey() bool {
	if o != nil && !IsNil(o.BannerKey) {
		return true
	}

	return false
}

// SetBannerKey gets a reference to the given string and assigns it to the BannerKey field.
func (o *UpdateOrganizationDataAttributes) SetBannerKey(v string) {
	o.BannerKey = &v
}

func (o UpdateOrganizationDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateOrganizationDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.IconKey) {
		toSerialize["icon_key"] = o.IconKey
	}
	if !IsNil(o.BannerKey) {
		toSerialize["banner_key"] = o.BannerKey
	}
	return toSerialize, nil
}

func (o *UpdateOrganizationDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateOrganizationDataAttributes := _UpdateOrganizationDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateOrganizationDataAttributes)

	if err != nil {
		return err
	}

	*o = UpdateOrganizationDataAttributes(varUpdateOrganizationDataAttributes)

	return err
}

type NullableUpdateOrganizationDataAttributes struct {
	value *UpdateOrganizationDataAttributes
	isSet bool
}

func (v NullableUpdateOrganizationDataAttributes) Get() *UpdateOrganizationDataAttributes {
	return v.value
}

func (v *NullableUpdateOrganizationDataAttributes) Set(val *UpdateOrganizationDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateOrganizationDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateOrganizationDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateOrganizationDataAttributes(val *UpdateOrganizationDataAttributes) *NullableUpdateOrganizationDataAttributes {
	return &NullableUpdateOrganizationDataAttributes{value: val, isSet: true}
}

func (v NullableUpdateOrganizationDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateOrganizationDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


