/*
organizations-svc API

API documentation for organizations-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InviteDataRelationshipsOrganization type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InviteDataRelationshipsOrganization{}

// InviteDataRelationshipsOrganization struct for InviteDataRelationshipsOrganization
type InviteDataRelationshipsOrganization struct {
	Data InviteDataRelationshipsOrganizationData `json:"data"`
}

type _InviteDataRelationshipsOrganization InviteDataRelationshipsOrganization

// NewInviteDataRelationshipsOrganization instantiates a new InviteDataRelationshipsOrganization object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInviteDataRelationshipsOrganization(data InviteDataRelationshipsOrganizationData) *InviteDataRelationshipsOrganization {
	this := InviteDataRelationshipsOrganization{}
	this.Data = data
	return &this
}

// NewInviteDataRelationshipsOrganizationWithDefaults instantiates a new InviteDataRelationshipsOrganization object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInviteDataRelationshipsOrganizationWithDefaults() *InviteDataRelationshipsOrganization {
	this := InviteDataRelationshipsOrganization{}
	return &this
}

// GetData returns the Data field value
func (o *InviteDataRelationshipsOrganization) GetData() InviteDataRelationshipsOrganizationData {
	if o == nil {
		var ret InviteDataRelationshipsOrganizationData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *InviteDataRelationshipsOrganization) GetDataOk() (*InviteDataRelationshipsOrganizationData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *InviteDataRelationshipsOrganization) SetData(v InviteDataRelationshipsOrganizationData) {
	o.Data = v
}

func (o InviteDataRelationshipsOrganization) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InviteDataRelationshipsOrganization) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *InviteDataRelationshipsOrganization) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInviteDataRelationshipsOrganization := _InviteDataRelationshipsOrganization{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInviteDataRelationshipsOrganization)

	if err != nil {
		return err
	}

	*o = InviteDataRelationshipsOrganization(varInviteDataRelationshipsOrganization)

	return err
}

type NullableInviteDataRelationshipsOrganization struct {
	value *InviteDataRelationshipsOrganization
	isSet bool
}

func (v NullableInviteDataRelationshipsOrganization) Get() *InviteDataRelationshipsOrganization {
	return v.value
}

func (v *NullableInviteDataRelationshipsOrganization) Set(val *InviteDataRelationshipsOrganization) {
	v.value = val
	v.isSet = true
}

func (v NullableInviteDataRelationshipsOrganization) IsSet() bool {
	return v.isSet
}

func (v *NullableInviteDataRelationshipsOrganization) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInviteDataRelationshipsOrganization(val *InviteDataRelationshipsOrganization) *NullableInviteDataRelationshipsOrganization {
	return &NullableInviteDataRelationshipsOrganization{value: val, isSet: true}
}

func (v NullableInviteDataRelationshipsOrganization) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInviteDataRelationshipsOrganization) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


