/*
organizations-svc API

API documentation for organizations-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"github.com/google/uuid"
	"bytes"
	"fmt"
)

// checks if the InviteDataRelationshipsOrganizationData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InviteDataRelationshipsOrganizationData{}

// InviteDataRelationshipsOrganizationData struct for InviteDataRelationshipsOrganizationData
type InviteDataRelationshipsOrganizationData struct {
	Type string `json:"type"`
	Id uuid.UUID `json:"id"`
}

type _InviteDataRelationshipsOrganizationData InviteDataRelationshipsOrganizationData

// NewInviteDataRelationshipsOrganizationData instantiates a new InviteDataRelationshipsOrganizationData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInviteDataRelationshipsOrganizationData(type_ string, id uuid.UUID) *InviteDataRelationshipsOrganizationData {
	this := InviteDataRelationshipsOrganizationData{}
	this.Type = type_
	this.Id = id
	return &this
}

// NewInviteDataRelationshipsOrganizationDataWithDefaults instantiates a new InviteDataRelationshipsOrganizationData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInviteDataRelationshipsOrganizationDataWithDefaults() *InviteDataRelationshipsOrganizationData {
	this := InviteDataRelationshipsOrganizationData{}
	return &this
}

// GetType returns the Type field value
func (o *InviteDataRelationshipsOrganizationData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *InviteDataRelationshipsOrganizationData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *InviteDataRelationshipsOrganizationData) SetType(v string) {
	o.Type = v
}

// GetId returns the Id field value
func (o *InviteDataRelationshipsOrganizationData) GetId() uuid.UUID {
	if o == nil {
		var ret uuid.UUID
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *InviteDataRelationshipsOrganizationData) GetIdOk() (*uuid.UUID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *InviteDataRelationshipsOrganizationData) SetId(v uuid.UUID) {
	o.Id = v
}

func (o InviteDataRelationshipsOrganizationData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InviteDataRelationshipsOrganizationData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *InviteDataRelationshipsOrganizationData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInviteDataRelationshipsOrganizationData := _InviteDataRelationshipsOrganizationData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInviteDataRelationshipsOrganizationData)

	if err != nil {
		return err
	}

	*o = InviteDataRelationshipsOrganizationData(varInviteDataRelationshipsOrganizationData)

	return err
}

type NullableInviteDataRelationshipsOrganizationData struct {
	value *InviteDataRelationshipsOrganizationData
	isSet bool
}

func (v NullableInviteDataRelationshipsOrganizationData) Get() *InviteDataRelationshipsOrganizationData {
	return v.value
}

func (v *NullableInviteDataRelationshipsOrganizationData) Set(val *InviteDataRelationshipsOrganizationData) {
	v.value = val
	v.isSet = true
}

func (v NullableInviteDataRelationshipsOrganizationData) IsSet() bool {
	return v.isSet
}

func (v *NullableInviteDataRelationshipsOrganizationData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInviteDataRelationshipsOrganizationData(val *InviteDataRelationshipsOrganizationData) *NullableInviteDataRelationshipsOrganizationData {
	return &NullableInviteDataRelationshipsOrganizationData{value: val, isSet: true}
}

func (v NullableInviteDataRelationshipsOrganizationData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInviteDataRelationshipsOrganizationData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


