/*
organizations-svc API

API documentation for organizations-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// MemberIncludedInner - struct for MemberIncludedInner
type MemberIncludedInner struct {
	OrganizationData *OrganizationData
	ProfileData *ProfileData
}

// OrganizationDataAsMemberIncludedInner is a convenience function that returns OrganizationData wrapped in MemberIncludedInner
func OrganizationDataAsMemberIncludedInner(v *OrganizationData) MemberIncludedInner {
	return MemberIncludedInner{
		OrganizationData: v,
	}
}

// ProfileDataAsMemberIncludedInner is a convenience function that returns ProfileData wrapped in MemberIncludedInner
func ProfileDataAsMemberIncludedInner(v *ProfileData) MemberIncludedInner {
	return MemberIncludedInner{
		ProfileData: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *MemberIncludedInner) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into OrganizationData
	err = newStrictDecoder(data).Decode(&dst.OrganizationData)
	if err == nil {
		jsonOrganizationData, _ := json.Marshal(dst.OrganizationData)
		if string(jsonOrganizationData) == "{}" { // empty struct
			dst.OrganizationData = nil
		} else {
			if err = validator.Validate(dst.OrganizationData); err != nil {
				dst.OrganizationData = nil
			} else {
				match++
			}
		}
	} else {
		dst.OrganizationData = nil
	}

	// try to unmarshal data into ProfileData
	err = newStrictDecoder(data).Decode(&dst.ProfileData)
	if err == nil {
		jsonProfileData, _ := json.Marshal(dst.ProfileData)
		if string(jsonProfileData) == "{}" { // empty struct
			dst.ProfileData = nil
		} else {
			if err = validator.Validate(dst.ProfileData); err != nil {
				dst.ProfileData = nil
			} else {
				match++
			}
		}
	} else {
		dst.ProfileData = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.OrganizationData = nil
		dst.ProfileData = nil

		return fmt.Errorf("data matches more than one schema in oneOf(MemberIncludedInner)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(MemberIncludedInner)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src MemberIncludedInner) MarshalJSON() ([]byte, error) {
	if src.OrganizationData != nil {
		return json.Marshal(&src.OrganizationData)
	}

	if src.ProfileData != nil {
		return json.Marshal(&src.ProfileData)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *MemberIncludedInner) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.OrganizationData != nil {
		return obj.OrganizationData
	}

	if obj.ProfileData != nil {
		return obj.ProfileData
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj MemberIncludedInner) GetActualInstanceValue() (interface{}) {
	if obj.OrganizationData != nil {
		return *obj.OrganizationData
	}

	if obj.ProfileData != nil {
		return *obj.ProfileData
	}

	// all schemas are nil
	return nil
}

type NullableMemberIncludedInner struct {
	value *MemberIncludedInner
	isSet bool
}

func (v NullableMemberIncludedInner) Get() *MemberIncludedInner {
	return v.value
}

func (v *NullableMemberIncludedInner) Set(val *MemberIncludedInner) {
	v.value = val
	v.isSet = true
}

func (v NullableMemberIncludedInner) IsSet() bool {
	return v.isSet
}

func (v *NullableMemberIncludedInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMemberIncludedInner(val *MemberIncludedInner) *NullableMemberIncludedInner {
	return &NullableMemberIncludedInner{value: val, isSet: true}
}

func (v NullableMemberIncludedInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMemberIncludedInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


