/*
organizations-svc API

API documentation for organizations-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"github.com/google/uuid"
	"bytes"
	"fmt"
)

// checks if the UploadOrgMediaLinksData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UploadOrgMediaLinksData{}

// UploadOrgMediaLinksData struct for UploadOrgMediaLinksData
type UploadOrgMediaLinksData struct {
	// organization id
	Id uuid.UUID `json:"id"`
	Type string `json:"type"`
	Attributes UploadOrgMediaLinksDataAttributes `json:"attributes"`
	Relationships UploadOrgMediaLinksDataRelationships `json:"relationships"`
}

type _UploadOrgMediaLinksData UploadOrgMediaLinksData

// NewUploadOrgMediaLinksData instantiates a new UploadOrgMediaLinksData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUploadOrgMediaLinksData(id uuid.UUID, type_ string, attributes UploadOrgMediaLinksDataAttributes, relationships UploadOrgMediaLinksDataRelationships) *UploadOrgMediaLinksData {
	this := UploadOrgMediaLinksData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	this.Relationships = relationships
	return &this
}

// NewUploadOrgMediaLinksDataWithDefaults instantiates a new UploadOrgMediaLinksData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUploadOrgMediaLinksDataWithDefaults() *UploadOrgMediaLinksData {
	this := UploadOrgMediaLinksData{}
	return &this
}

// GetId returns the Id field value
func (o *UploadOrgMediaLinksData) GetId() uuid.UUID {
	if o == nil {
		var ret uuid.UUID
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UploadOrgMediaLinksData) GetIdOk() (*uuid.UUID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UploadOrgMediaLinksData) SetId(v uuid.UUID) {
	o.Id = v
}

// GetType returns the Type field value
func (o *UploadOrgMediaLinksData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *UploadOrgMediaLinksData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *UploadOrgMediaLinksData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *UploadOrgMediaLinksData) GetAttributes() UploadOrgMediaLinksDataAttributes {
	if o == nil {
		var ret UploadOrgMediaLinksDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *UploadOrgMediaLinksData) GetAttributesOk() (*UploadOrgMediaLinksDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *UploadOrgMediaLinksData) SetAttributes(v UploadOrgMediaLinksDataAttributes) {
	o.Attributes = v
}

// GetRelationships returns the Relationships field value
func (o *UploadOrgMediaLinksData) GetRelationships() UploadOrgMediaLinksDataRelationships {
	if o == nil {
		var ret UploadOrgMediaLinksDataRelationships
		return ret
	}

	return o.Relationships
}

// GetRelationshipsOk returns a tuple with the Relationships field value
// and a boolean to check if the value has been set.
func (o *UploadOrgMediaLinksData) GetRelationshipsOk() (*UploadOrgMediaLinksDataRelationships, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Relationships, true
}

// SetRelationships sets field value
func (o *UploadOrgMediaLinksData) SetRelationships(v UploadOrgMediaLinksDataRelationships) {
	o.Relationships = v
}

func (o UploadOrgMediaLinksData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UploadOrgMediaLinksData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	toSerialize["relationships"] = o.Relationships
	return toSerialize, nil
}

func (o *UploadOrgMediaLinksData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
		"relationships",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUploadOrgMediaLinksData := _UploadOrgMediaLinksData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUploadOrgMediaLinksData)

	if err != nil {
		return err
	}

	*o = UploadOrgMediaLinksData(varUploadOrgMediaLinksData)

	return err
}

type NullableUploadOrgMediaLinksData struct {
	value *UploadOrgMediaLinksData
	isSet bool
}

func (v NullableUploadOrgMediaLinksData) Get() *UploadOrgMediaLinksData {
	return v.value
}

func (v *NullableUploadOrgMediaLinksData) Set(val *UploadOrgMediaLinksData) {
	v.value = val
	v.isSet = true
}

func (v NullableUploadOrgMediaLinksData) IsSet() bool {
	return v.isSet
}

func (v *NullableUploadOrgMediaLinksData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUploadOrgMediaLinksData(val *UploadOrgMediaLinksData) *NullableUploadOrgMediaLinksData {
	return &NullableUploadOrgMediaLinksData{value: val, isSet: true}
}

func (v NullableUploadOrgMediaLinksData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUploadOrgMediaLinksData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


