/*
NetBill organizations-svc API

API documentation for organizations-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"github.com/google/uuid"
	"bytes"
	"fmt"
)

// checks if the MemberDataRelationshipsProfileData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MemberDataRelationshipsProfileData{}

// MemberDataRelationshipsProfileData struct for MemberDataRelationshipsProfileData
type MemberDataRelationshipsProfileData struct {
	Type string `json:"type"`
	Id uuid.UUID `json:"id"`
}

type _MemberDataRelationshipsProfileData MemberDataRelationshipsProfileData

// NewMemberDataRelationshipsProfileData instantiates a new MemberDataRelationshipsProfileData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMemberDataRelationshipsProfileData(type_ string, id uuid.UUID) *MemberDataRelationshipsProfileData {
	this := MemberDataRelationshipsProfileData{}
	this.Type = type_
	this.Id = id
	return &this
}

// NewMemberDataRelationshipsProfileDataWithDefaults instantiates a new MemberDataRelationshipsProfileData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMemberDataRelationshipsProfileDataWithDefaults() *MemberDataRelationshipsProfileData {
	this := MemberDataRelationshipsProfileData{}
	return &this
}

// GetType returns the Type field value
func (o *MemberDataRelationshipsProfileData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *MemberDataRelationshipsProfileData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *MemberDataRelationshipsProfileData) SetType(v string) {
	o.Type = v
}

// GetId returns the Id field value
func (o *MemberDataRelationshipsProfileData) GetId() uuid.UUID {
	if o == nil {
		var ret uuid.UUID
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *MemberDataRelationshipsProfileData) GetIdOk() (*uuid.UUID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *MemberDataRelationshipsProfileData) SetId(v uuid.UUID) {
	o.Id = v
}

func (o MemberDataRelationshipsProfileData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MemberDataRelationshipsProfileData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *MemberDataRelationshipsProfileData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMemberDataRelationshipsProfileData := _MemberDataRelationshipsProfileData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMemberDataRelationshipsProfileData)

	if err != nil {
		return err
	}

	*o = MemberDataRelationshipsProfileData(varMemberDataRelationshipsProfileData)

	return err
}

type NullableMemberDataRelationshipsProfileData struct {
	value *MemberDataRelationshipsProfileData
	isSet bool
}

func (v NullableMemberDataRelationshipsProfileData) Get() *MemberDataRelationshipsProfileData {
	return v.value
}

func (v *NullableMemberDataRelationshipsProfileData) Set(val *MemberDataRelationshipsProfileData) {
	v.value = val
	v.isSet = true
}

func (v NullableMemberDataRelationshipsProfileData) IsSet() bool {
	return v.isSet
}

func (v *NullableMemberDataRelationshipsProfileData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMemberDataRelationshipsProfileData(val *MemberDataRelationshipsProfileData) *NullableMemberDataRelationshipsProfileData {
	return &NullableMemberDataRelationshipsProfileData{value: val, isSet: true}
}

func (v NullableMemberDataRelationshipsProfileData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMemberDataRelationshipsProfileData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


