/*
organizations-svc API

API documentation for organizations-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeleteUploadOrgIconDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteUploadOrgIconDataAttributes{}

// DeleteUploadOrgIconDataAttributes struct for DeleteUploadOrgIconDataAttributes
type DeleteUploadOrgIconDataAttributes struct {
	// icon media key
	IconKey string `json:"icon_key"`
}

type _DeleteUploadOrgIconDataAttributes DeleteUploadOrgIconDataAttributes

// NewDeleteUploadOrgIconDataAttributes instantiates a new DeleteUploadOrgIconDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteUploadOrgIconDataAttributes(iconKey string) *DeleteUploadOrgIconDataAttributes {
	this := DeleteUploadOrgIconDataAttributes{}
	this.IconKey = iconKey
	return &this
}

// NewDeleteUploadOrgIconDataAttributesWithDefaults instantiates a new DeleteUploadOrgIconDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteUploadOrgIconDataAttributesWithDefaults() *DeleteUploadOrgIconDataAttributes {
	this := DeleteUploadOrgIconDataAttributes{}
	return &this
}

// GetIconKey returns the IconKey field value
func (o *DeleteUploadOrgIconDataAttributes) GetIconKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IconKey
}

// GetIconKeyOk returns a tuple with the IconKey field value
// and a boolean to check if the value has been set.
func (o *DeleteUploadOrgIconDataAttributes) GetIconKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IconKey, true
}

// SetIconKey sets field value
func (o *DeleteUploadOrgIconDataAttributes) SetIconKey(v string) {
	o.IconKey = v
}

func (o DeleteUploadOrgIconDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteUploadOrgIconDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["icon_key"] = o.IconKey
	return toSerialize, nil
}

func (o *DeleteUploadOrgIconDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"icon_key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeleteUploadOrgIconDataAttributes := _DeleteUploadOrgIconDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeleteUploadOrgIconDataAttributes)

	if err != nil {
		return err
	}

	*o = DeleteUploadOrgIconDataAttributes(varDeleteUploadOrgIconDataAttributes)

	return err
}

type NullableDeleteUploadOrgIconDataAttributes struct {
	value *DeleteUploadOrgIconDataAttributes
	isSet bool
}

func (v NullableDeleteUploadOrgIconDataAttributes) Get() *DeleteUploadOrgIconDataAttributes {
	return v.value
}

func (v *NullableDeleteUploadOrgIconDataAttributes) Set(val *DeleteUploadOrgIconDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteUploadOrgIconDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteUploadOrgIconDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteUploadOrgIconDataAttributes(val *DeleteUploadOrgIconDataAttributes) *NullableDeleteUploadOrgIconDataAttributes {
	return &NullableDeleteUploadOrgIconDataAttributes{value: val, isSet: true}
}

func (v NullableDeleteUploadOrgIconDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteUploadOrgIconDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


