/*
organizations-svc API

API documentation for organizations-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InviteDataRelationshipsInvitee type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InviteDataRelationshipsInvitee{}

// InviteDataRelationshipsInvitee struct for InviteDataRelationshipsInvitee
type InviteDataRelationshipsInvitee struct {
	Data InviteDataRelationshipsInviteeData `json:"data"`
}

type _InviteDataRelationshipsInvitee InviteDataRelationshipsInvitee

// NewInviteDataRelationshipsInvitee instantiates a new InviteDataRelationshipsInvitee object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInviteDataRelationshipsInvitee(data InviteDataRelationshipsInviteeData) *InviteDataRelationshipsInvitee {
	this := InviteDataRelationshipsInvitee{}
	this.Data = data
	return &this
}

// NewInviteDataRelationshipsInviteeWithDefaults instantiates a new InviteDataRelationshipsInvitee object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInviteDataRelationshipsInviteeWithDefaults() *InviteDataRelationshipsInvitee {
	this := InviteDataRelationshipsInvitee{}
	return &this
}

// GetData returns the Data field value
func (o *InviteDataRelationshipsInvitee) GetData() InviteDataRelationshipsInviteeData {
	if o == nil {
		var ret InviteDataRelationshipsInviteeData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *InviteDataRelationshipsInvitee) GetDataOk() (*InviteDataRelationshipsInviteeData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *InviteDataRelationshipsInvitee) SetData(v InviteDataRelationshipsInviteeData) {
	o.Data = v
}

func (o InviteDataRelationshipsInvitee) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InviteDataRelationshipsInvitee) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *InviteDataRelationshipsInvitee) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInviteDataRelationshipsInvitee := _InviteDataRelationshipsInvitee{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInviteDataRelationshipsInvitee)

	if err != nil {
		return err
	}

	*o = InviteDataRelationshipsInvitee(varInviteDataRelationshipsInvitee)

	return err
}

type NullableInviteDataRelationshipsInvitee struct {
	value *InviteDataRelationshipsInvitee
	isSet bool
}

func (v NullableInviteDataRelationshipsInvitee) Get() *InviteDataRelationshipsInvitee {
	return v.value
}

func (v *NullableInviteDataRelationshipsInvitee) Set(val *InviteDataRelationshipsInvitee) {
	v.value = val
	v.isSet = true
}

func (v NullableInviteDataRelationshipsInvitee) IsSet() bool {
	return v.isSet
}

func (v *NullableInviteDataRelationshipsInvitee) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInviteDataRelationshipsInvitee(val *InviteDataRelationshipsInvitee) *NullableInviteDataRelationshipsInvitee {
	return &NullableInviteDataRelationshipsInvitee{value: val, isSet: true}
}

func (v NullableInviteDataRelationshipsInvitee) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInviteDataRelationshipsInvitee) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


