/*
NetBill organizations-svc API

API documentation for organizations-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MemberDataRelationshipsProfile type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MemberDataRelationshipsProfile{}

// MemberDataRelationshipsProfile struct for MemberDataRelationshipsProfile
type MemberDataRelationshipsProfile struct {
	Data MemberDataRelationshipsProfileData `json:"data"`
}

type _MemberDataRelationshipsProfile MemberDataRelationshipsProfile

// NewMemberDataRelationshipsProfile instantiates a new MemberDataRelationshipsProfile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMemberDataRelationshipsProfile(data MemberDataRelationshipsProfileData) *MemberDataRelationshipsProfile {
	this := MemberDataRelationshipsProfile{}
	this.Data = data
	return &this
}

// NewMemberDataRelationshipsProfileWithDefaults instantiates a new MemberDataRelationshipsProfile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMemberDataRelationshipsProfileWithDefaults() *MemberDataRelationshipsProfile {
	this := MemberDataRelationshipsProfile{}
	return &this
}

// GetData returns the Data field value
func (o *MemberDataRelationshipsProfile) GetData() MemberDataRelationshipsProfileData {
	if o == nil {
		var ret MemberDataRelationshipsProfileData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *MemberDataRelationshipsProfile) GetDataOk() (*MemberDataRelationshipsProfileData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *MemberDataRelationshipsProfile) SetData(v MemberDataRelationshipsProfileData) {
	o.Data = v
}

func (o MemberDataRelationshipsProfile) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MemberDataRelationshipsProfile) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *MemberDataRelationshipsProfile) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMemberDataRelationshipsProfile := _MemberDataRelationshipsProfile{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMemberDataRelationshipsProfile)

	if err != nil {
		return err
	}

	*o = MemberDataRelationshipsProfile(varMemberDataRelationshipsProfile)

	return err
}

type NullableMemberDataRelationshipsProfile struct {
	value *MemberDataRelationshipsProfile
	isSet bool
}

func (v NullableMemberDataRelationshipsProfile) Get() *MemberDataRelationshipsProfile {
	return v.value
}

func (v *NullableMemberDataRelationshipsProfile) Set(val *MemberDataRelationshipsProfile) {
	v.value = val
	v.isSet = true
}

func (v NullableMemberDataRelationshipsProfile) IsSet() bool {
	return v.isSet
}

func (v *NullableMemberDataRelationshipsProfile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMemberDataRelationshipsProfile(val *MemberDataRelationshipsProfile) *NullableMemberDataRelationshipsProfile {
	return &NullableMemberDataRelationshipsProfile{value: val, isSet: true}
}

func (v NullableMemberDataRelationshipsProfile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMemberDataRelationshipsProfile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


