/*
organizations-svc API

API documentation for organizations-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InviteDataRelationships type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InviteDataRelationships{}

// InviteDataRelationships struct for InviteDataRelationships
type InviteDataRelationships struct {
	Organization InviteDataRelationshipsOrganization `json:"organization"`
	Invitee InviteDataRelationshipsInvitee `json:"invitee"`
}

type _InviteDataRelationships InviteDataRelationships

// NewInviteDataRelationships instantiates a new InviteDataRelationships object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInviteDataRelationships(organization InviteDataRelationshipsOrganization, invitee InviteDataRelationshipsInvitee) *InviteDataRelationships {
	this := InviteDataRelationships{}
	this.Organization = organization
	this.Invitee = invitee
	return &this
}

// NewInviteDataRelationshipsWithDefaults instantiates a new InviteDataRelationships object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInviteDataRelationshipsWithDefaults() *InviteDataRelationships {
	this := InviteDataRelationships{}
	return &this
}

// GetOrganization returns the Organization field value
func (o *InviteDataRelationships) GetOrganization() InviteDataRelationshipsOrganization {
	if o == nil {
		var ret InviteDataRelationshipsOrganization
		return ret
	}

	return o.Organization
}

// GetOrganizationOk returns a tuple with the Organization field value
// and a boolean to check if the value has been set.
func (o *InviteDataRelationships) GetOrganizationOk() (*InviteDataRelationshipsOrganization, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Organization, true
}

// SetOrganization sets field value
func (o *InviteDataRelationships) SetOrganization(v InviteDataRelationshipsOrganization) {
	o.Organization = v
}

// GetInvitee returns the Invitee field value
func (o *InviteDataRelationships) GetInvitee() InviteDataRelationshipsInvitee {
	if o == nil {
		var ret InviteDataRelationshipsInvitee
		return ret
	}

	return o.Invitee
}

// GetInviteeOk returns a tuple with the Invitee field value
// and a boolean to check if the value has been set.
func (o *InviteDataRelationships) GetInviteeOk() (*InviteDataRelationshipsInvitee, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Invitee, true
}

// SetInvitee sets field value
func (o *InviteDataRelationships) SetInvitee(v InviteDataRelationshipsInvitee) {
	o.Invitee = v
}

func (o InviteDataRelationships) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InviteDataRelationships) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["organization"] = o.Organization
	toSerialize["invitee"] = o.Invitee
	return toSerialize, nil
}

func (o *InviteDataRelationships) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"organization",
		"invitee",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInviteDataRelationships := _InviteDataRelationships{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInviteDataRelationships)

	if err != nil {
		return err
	}

	*o = InviteDataRelationships(varInviteDataRelationships)

	return err
}

type NullableInviteDataRelationships struct {
	value *InviteDataRelationships
	isSet bool
}

func (v NullableInviteDataRelationships) Get() *InviteDataRelationships {
	return v.value
}

func (v *NullableInviteDataRelationships) Set(val *InviteDataRelationships) {
	v.value = val
	v.isSet = true
}

func (v NullableInviteDataRelationships) IsSet() bool {
	return v.isSet
}

func (v *NullableInviteDataRelationships) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInviteDataRelationships(val *InviteDataRelationships) *NullableInviteDataRelationships {
	return &NullableInviteDataRelationships{value: val, isSet: true}
}

func (v NullableInviteDataRelationships) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInviteDataRelationships) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


