/*
organizations-svc API

API documentation for organizations-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UploadOrgMediaLinks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UploadOrgMediaLinks{}

// UploadOrgMediaLinks struct for UploadOrgMediaLinks
type UploadOrgMediaLinks struct {
	Data UploadOrgMediaLinksData `json:"data"`
	Included []OrganizationData `json:"included"`
}

type _UploadOrgMediaLinks UploadOrgMediaLinks

// NewUploadOrgMediaLinks instantiates a new UploadOrgMediaLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUploadOrgMediaLinks(data UploadOrgMediaLinksData, included []OrganizationData) *UploadOrgMediaLinks {
	this := UploadOrgMediaLinks{}
	this.Data = data
	this.Included = included
	return &this
}

// NewUploadOrgMediaLinksWithDefaults instantiates a new UploadOrgMediaLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUploadOrgMediaLinksWithDefaults() *UploadOrgMediaLinks {
	this := UploadOrgMediaLinks{}
	return &this
}

// GetData returns the Data field value
func (o *UploadOrgMediaLinks) GetData() UploadOrgMediaLinksData {
	if o == nil {
		var ret UploadOrgMediaLinksData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UploadOrgMediaLinks) GetDataOk() (*UploadOrgMediaLinksData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *UploadOrgMediaLinks) SetData(v UploadOrgMediaLinksData) {
	o.Data = v
}

// GetIncluded returns the Included field value
func (o *UploadOrgMediaLinks) GetIncluded() []OrganizationData {
	if o == nil {
		var ret []OrganizationData
		return ret
	}

	return o.Included
}

// GetIncludedOk returns a tuple with the Included field value
// and a boolean to check if the value has been set.
func (o *UploadOrgMediaLinks) GetIncludedOk() ([]OrganizationData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Included, true
}

// SetIncluded sets field value
func (o *UploadOrgMediaLinks) SetIncluded(v []OrganizationData) {
	o.Included = v
}

func (o UploadOrgMediaLinks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UploadOrgMediaLinks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["included"] = o.Included
	return toSerialize, nil
}

func (o *UploadOrgMediaLinks) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"included",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUploadOrgMediaLinks := _UploadOrgMediaLinks{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUploadOrgMediaLinks)

	if err != nil {
		return err
	}

	*o = UploadOrgMediaLinks(varUploadOrgMediaLinks)

	return err
}

type NullableUploadOrgMediaLinks struct {
	value *UploadOrgMediaLinks
	isSet bool
}

func (v NullableUploadOrgMediaLinks) Get() *UploadOrgMediaLinks {
	return v.value
}

func (v *NullableUploadOrgMediaLinks) Set(val *UploadOrgMediaLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableUploadOrgMediaLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableUploadOrgMediaLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUploadOrgMediaLinks(val *UploadOrgMediaLinks) *NullableUploadOrgMediaLinks {
	return &NullableUploadOrgMediaLinks{value: val, isSet: true}
}

func (v NullableUploadOrgMediaLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUploadOrgMediaLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


