/*
organizations-svc API

API documentation for organizations-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeleteUploadOrgIcon type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteUploadOrgIcon{}

// DeleteUploadOrgIcon struct for DeleteUploadOrgIcon
type DeleteUploadOrgIcon struct {
	Data DeleteUploadOrgIconData `json:"data"`
}

type _DeleteUploadOrgIcon DeleteUploadOrgIcon

// NewDeleteUploadOrgIcon instantiates a new DeleteUploadOrgIcon object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteUploadOrgIcon(data DeleteUploadOrgIconData) *DeleteUploadOrgIcon {
	this := DeleteUploadOrgIcon{}
	this.Data = data
	return &this
}

// NewDeleteUploadOrgIconWithDefaults instantiates a new DeleteUploadOrgIcon object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteUploadOrgIconWithDefaults() *DeleteUploadOrgIcon {
	this := DeleteUploadOrgIcon{}
	return &this
}

// GetData returns the Data field value
func (o *DeleteUploadOrgIcon) GetData() DeleteUploadOrgIconData {
	if o == nil {
		var ret DeleteUploadOrgIconData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *DeleteUploadOrgIcon) GetDataOk() (*DeleteUploadOrgIconData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *DeleteUploadOrgIcon) SetData(v DeleteUploadOrgIconData) {
	o.Data = v
}

func (o DeleteUploadOrgIcon) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteUploadOrgIcon) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *DeleteUploadOrgIcon) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeleteUploadOrgIcon := _DeleteUploadOrgIcon{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeleteUploadOrgIcon)

	if err != nil {
		return err
	}

	*o = DeleteUploadOrgIcon(varDeleteUploadOrgIcon)

	return err
}

type NullableDeleteUploadOrgIcon struct {
	value *DeleteUploadOrgIcon
	isSet bool
}

func (v NullableDeleteUploadOrgIcon) Get() *DeleteUploadOrgIcon {
	return v.value
}

func (v *NullableDeleteUploadOrgIcon) Set(val *DeleteUploadOrgIcon) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteUploadOrgIcon) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteUploadOrgIcon) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteUploadOrgIcon(val *DeleteUploadOrgIcon) *NullableDeleteUploadOrgIcon {
	return &NullableDeleteUploadOrgIcon{value: val, isSet: true}
}

func (v NullableDeleteUploadOrgIcon) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteUploadOrgIcon) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


