/*
organizations-svc API

API documentation for organizations-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// InviteIncludedInner - Included related resources  for invites (e.g., organization, profile)
type InviteIncludedInner struct {
	OrganizationData *OrganizationData
	ProfileData *ProfileData
}

// OrganizationDataAsInviteIncludedInner is a convenience function that returns OrganizationData wrapped in InviteIncludedInner
func OrganizationDataAsInviteIncludedInner(v *OrganizationData) InviteIncludedInner {
	return InviteIncludedInner{
		OrganizationData: v,
	}
}

// ProfileDataAsInviteIncludedInner is a convenience function that returns ProfileData wrapped in InviteIncludedInner
func ProfileDataAsInviteIncludedInner(v *ProfileData) InviteIncludedInner {
	return InviteIncludedInner{
		ProfileData: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *InviteIncludedInner) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into OrganizationData
	err = newStrictDecoder(data).Decode(&dst.OrganizationData)
	if err == nil {
		jsonOrganizationData, _ := json.Marshal(dst.OrganizationData)
		if string(jsonOrganizationData) == "{}" { // empty struct
			dst.OrganizationData = nil
		} else {
			if err = validator.Validate(dst.OrganizationData); err != nil {
				dst.OrganizationData = nil
			} else {
				match++
			}
		}
	} else {
		dst.OrganizationData = nil
	}

	// try to unmarshal data into ProfileData
	err = newStrictDecoder(data).Decode(&dst.ProfileData)
	if err == nil {
		jsonProfileData, _ := json.Marshal(dst.ProfileData)
		if string(jsonProfileData) == "{}" { // empty struct
			dst.ProfileData = nil
		} else {
			if err = validator.Validate(dst.ProfileData); err != nil {
				dst.ProfileData = nil
			} else {
				match++
			}
		}
	} else {
		dst.ProfileData = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.OrganizationData = nil
		dst.ProfileData = nil

		return fmt.Errorf("data matches more than one schema in oneOf(InviteIncludedInner)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(InviteIncludedInner)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src InviteIncludedInner) MarshalJSON() ([]byte, error) {
	if src.OrganizationData != nil {
		return json.Marshal(&src.OrganizationData)
	}

	if src.ProfileData != nil {
		return json.Marshal(&src.ProfileData)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *InviteIncludedInner) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.OrganizationData != nil {
		return obj.OrganizationData
	}

	if obj.ProfileData != nil {
		return obj.ProfileData
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj InviteIncludedInner) GetActualInstanceValue() (interface{}) {
	if obj.OrganizationData != nil {
		return *obj.OrganizationData
	}

	if obj.ProfileData != nil {
		return *obj.ProfileData
	}

	// all schemas are nil
	return nil
}

type NullableInviteIncludedInner struct {
	value *InviteIncludedInner
	isSet bool
}

func (v NullableInviteIncludedInner) Get() *InviteIncludedInner {
	return v.value
}

func (v *NullableInviteIncludedInner) Set(val *InviteIncludedInner) {
	v.value = val
	v.isSet = true
}

func (v NullableInviteIncludedInner) IsSet() bool {
	return v.isSet
}

func (v *NullableInviteIncludedInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInviteIncludedInner(val *InviteIncludedInner) *NullableInviteIncludedInner {
	return &NullableInviteIncludedInner{value: val, isSet: true}
}

func (v NullableInviteIncludedInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInviteIncludedInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


