/*
NetBill organizations-svc API

API documentation for organizations-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeleteUploadOrgBanner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteUploadOrgBanner{}

// DeleteUploadOrgBanner struct for DeleteUploadOrgBanner
type DeleteUploadOrgBanner struct {
	Data DeleteUploadOrgBannerData `json:"data"`
}

type _DeleteUploadOrgBanner DeleteUploadOrgBanner

// NewDeleteUploadOrgBanner instantiates a new DeleteUploadOrgBanner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteUploadOrgBanner(data DeleteUploadOrgBannerData) *DeleteUploadOrgBanner {
	this := DeleteUploadOrgBanner{}
	this.Data = data
	return &this
}

// NewDeleteUploadOrgBannerWithDefaults instantiates a new DeleteUploadOrgBanner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteUploadOrgBannerWithDefaults() *DeleteUploadOrgBanner {
	this := DeleteUploadOrgBanner{}
	return &this
}

// GetData returns the Data field value
func (o *DeleteUploadOrgBanner) GetData() DeleteUploadOrgBannerData {
	if o == nil {
		var ret DeleteUploadOrgBannerData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *DeleteUploadOrgBanner) GetDataOk() (*DeleteUploadOrgBannerData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *DeleteUploadOrgBanner) SetData(v DeleteUploadOrgBannerData) {
	o.Data = v
}

func (o DeleteUploadOrgBanner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteUploadOrgBanner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *DeleteUploadOrgBanner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeleteUploadOrgBanner := _DeleteUploadOrgBanner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeleteUploadOrgBanner)

	if err != nil {
		return err
	}

	*o = DeleteUploadOrgBanner(varDeleteUploadOrgBanner)

	return err
}

type NullableDeleteUploadOrgBanner struct {
	value *DeleteUploadOrgBanner
	isSet bool
}

func (v NullableDeleteUploadOrgBanner) Get() *DeleteUploadOrgBanner {
	return v.value
}

func (v *NullableDeleteUploadOrgBanner) Set(val *DeleteUploadOrgBanner) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteUploadOrgBanner) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteUploadOrgBanner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteUploadOrgBanner(val *DeleteUploadOrgBanner) *NullableDeleteUploadOrgBanner {
	return &NullableDeleteUploadOrgBanner{value: val, isSet: true}
}

func (v NullableDeleteUploadOrgBanner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteUploadOrgBanner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


