/*
organizations-svc API

API documentation for organizations-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// checks if the UploadOrgMediaLinksDataRelationships type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UploadOrgMediaLinksDataRelationships{}

// UploadOrgMediaLinksDataRelationships struct for UploadOrgMediaLinksDataRelationships
type UploadOrgMediaLinksDataRelationships struct {
	Organization *UploadOrgMediaLinksDataRelationshipsOrganization `json:"organization,omitempty"`
}

// NewUploadOrgMediaLinksDataRelationships instantiates a new UploadOrgMediaLinksDataRelationships object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUploadOrgMediaLinksDataRelationships() *UploadOrgMediaLinksDataRelationships {
	this := UploadOrgMediaLinksDataRelationships{}
	return &this
}

// NewUploadOrgMediaLinksDataRelationshipsWithDefaults instantiates a new UploadOrgMediaLinksDataRelationships object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUploadOrgMediaLinksDataRelationshipsWithDefaults() *UploadOrgMediaLinksDataRelationships {
	this := UploadOrgMediaLinksDataRelationships{}
	return &this
}

// GetOrganization returns the Organization field value if set, zero value otherwise.
func (o *UploadOrgMediaLinksDataRelationships) GetOrganization() UploadOrgMediaLinksDataRelationshipsOrganization {
	if o == nil || IsNil(o.Organization) {
		var ret UploadOrgMediaLinksDataRelationshipsOrganization
		return ret
	}
	return *o.Organization
}

// GetOrganizationOk returns a tuple with the Organization field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UploadOrgMediaLinksDataRelationships) GetOrganizationOk() (*UploadOrgMediaLinksDataRelationshipsOrganization, bool) {
	if o == nil || IsNil(o.Organization) {
		return nil, false
	}
	return o.Organization, true
}

// HasOrganization returns a boolean if a field has been set.
func (o *UploadOrgMediaLinksDataRelationships) HasOrganization() bool {
	if o != nil && !IsNil(o.Organization) {
		return true
	}

	return false
}

// SetOrganization gets a reference to the given UploadOrgMediaLinksDataRelationshipsOrganization and assigns it to the Organization field.
func (o *UploadOrgMediaLinksDataRelationships) SetOrganization(v UploadOrgMediaLinksDataRelationshipsOrganization) {
	o.Organization = &v
}

func (o UploadOrgMediaLinksDataRelationships) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UploadOrgMediaLinksDataRelationships) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Organization) {
		toSerialize["organization"] = o.Organization
	}
	return toSerialize, nil
}

type NullableUploadOrgMediaLinksDataRelationships struct {
	value *UploadOrgMediaLinksDataRelationships
	isSet bool
}

func (v NullableUploadOrgMediaLinksDataRelationships) Get() *UploadOrgMediaLinksDataRelationships {
	return v.value
}

func (v *NullableUploadOrgMediaLinksDataRelationships) Set(val *UploadOrgMediaLinksDataRelationships) {
	v.value = val
	v.isSet = true
}

func (v NullableUploadOrgMediaLinksDataRelationships) IsSet() bool {
	return v.isSet
}

func (v *NullableUploadOrgMediaLinksDataRelationships) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUploadOrgMediaLinksDataRelationships(val *UploadOrgMediaLinksDataRelationships) *NullableUploadOrgMediaLinksDataRelationships {
	return &NullableUploadOrgMediaLinksDataRelationships{value: val, isSet: true}
}

func (v NullableUploadOrgMediaLinksDataRelationships) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUploadOrgMediaLinksDataRelationships) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


