/*
agglomerations-svc API

API documentation for agglomerations-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateRolePermissionsDataAttributesRolesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateRolePermissionsDataAttributesRolesInner{}

// UpdateRolePermissionsDataAttributesRolesInner struct for UpdateRolePermissionsDataAttributesRolesInner
type UpdateRolePermissionsDataAttributesRolesInner struct {
	// permission code
	Code string `json:"code"`
	// The new status of the permission for the role
	Status bool `json:"status"`
}

type _UpdateRolePermissionsDataAttributesRolesInner UpdateRolePermissionsDataAttributesRolesInner

// NewUpdateRolePermissionsDataAttributesRolesInner instantiates a new UpdateRolePermissionsDataAttributesRolesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateRolePermissionsDataAttributesRolesInner(code string, status bool) *UpdateRolePermissionsDataAttributesRolesInner {
	this := UpdateRolePermissionsDataAttributesRolesInner{}
	this.Code = code
	this.Status = status
	return &this
}

// NewUpdateRolePermissionsDataAttributesRolesInnerWithDefaults instantiates a new UpdateRolePermissionsDataAttributesRolesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateRolePermissionsDataAttributesRolesInnerWithDefaults() *UpdateRolePermissionsDataAttributesRolesInner {
	this := UpdateRolePermissionsDataAttributesRolesInner{}
	return &this
}

// GetCode returns the Code field value
func (o *UpdateRolePermissionsDataAttributesRolesInner) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *UpdateRolePermissionsDataAttributesRolesInner) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *UpdateRolePermissionsDataAttributesRolesInner) SetCode(v string) {
	o.Code = v
}

// GetStatus returns the Status field value
func (o *UpdateRolePermissionsDataAttributesRolesInner) GetStatus() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *UpdateRolePermissionsDataAttributesRolesInner) GetStatusOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *UpdateRolePermissionsDataAttributesRolesInner) SetStatus(v bool) {
	o.Status = v
}

func (o UpdateRolePermissionsDataAttributesRolesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateRolePermissionsDataAttributesRolesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *UpdateRolePermissionsDataAttributesRolesInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateRolePermissionsDataAttributesRolesInner := _UpdateRolePermissionsDataAttributesRolesInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateRolePermissionsDataAttributesRolesInner)

	if err != nil {
		return err
	}

	*o = UpdateRolePermissionsDataAttributesRolesInner(varUpdateRolePermissionsDataAttributesRolesInner)

	return err
}

type NullableUpdateRolePermissionsDataAttributesRolesInner struct {
	value *UpdateRolePermissionsDataAttributesRolesInner
	isSet bool
}

func (v NullableUpdateRolePermissionsDataAttributesRolesInner) Get() *UpdateRolePermissionsDataAttributesRolesInner {
	return v.value
}

func (v *NullableUpdateRolePermissionsDataAttributesRolesInner) Set(val *UpdateRolePermissionsDataAttributesRolesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateRolePermissionsDataAttributesRolesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateRolePermissionsDataAttributesRolesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateRolePermissionsDataAttributesRolesInner(val *UpdateRolePermissionsDataAttributesRolesInner) *NullableUpdateRolePermissionsDataAttributesRolesInner {
	return &NullableUpdateRolePermissionsDataAttributesRolesInner{value: val, isSet: true}
}

func (v NullableUpdateRolePermissionsDataAttributesRolesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateRolePermissionsDataAttributesRolesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


