/*
organizations-svc API

API documentation for organizations-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateRolePermissionsDataAttributesPermissionsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateRolePermissionsDataAttributesPermissionsInner{}

// UpdateRolePermissionsDataAttributesPermissionsInner struct for UpdateRolePermissionsDataAttributesPermissionsInner
type UpdateRolePermissionsDataAttributesPermissionsInner struct {
	// permission code
	Code string `json:"code"`
	// The new status of the permission for the role
	Status bool `json:"status"`
}

type _UpdateRolePermissionsDataAttributesPermissionsInner UpdateRolePermissionsDataAttributesPermissionsInner

// NewUpdateRolePermissionsDataAttributesPermissionsInner instantiates a new UpdateRolePermissionsDataAttributesPermissionsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateRolePermissionsDataAttributesPermissionsInner(code string, status bool) *UpdateRolePermissionsDataAttributesPermissionsInner {
	this := UpdateRolePermissionsDataAttributesPermissionsInner{}
	this.Code = code
	this.Status = status
	return &this
}

// NewUpdateRolePermissionsDataAttributesPermissionsInnerWithDefaults instantiates a new UpdateRolePermissionsDataAttributesPermissionsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateRolePermissionsDataAttributesPermissionsInnerWithDefaults() *UpdateRolePermissionsDataAttributesPermissionsInner {
	this := UpdateRolePermissionsDataAttributesPermissionsInner{}
	return &this
}

// GetCode returns the Code field value
func (o *UpdateRolePermissionsDataAttributesPermissionsInner) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *UpdateRolePermissionsDataAttributesPermissionsInner) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *UpdateRolePermissionsDataAttributesPermissionsInner) SetCode(v string) {
	o.Code = v
}

// GetStatus returns the Status field value
func (o *UpdateRolePermissionsDataAttributesPermissionsInner) GetStatus() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *UpdateRolePermissionsDataAttributesPermissionsInner) GetStatusOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *UpdateRolePermissionsDataAttributesPermissionsInner) SetStatus(v bool) {
	o.Status = v
}

func (o UpdateRolePermissionsDataAttributesPermissionsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateRolePermissionsDataAttributesPermissionsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *UpdateRolePermissionsDataAttributesPermissionsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateRolePermissionsDataAttributesPermissionsInner := _UpdateRolePermissionsDataAttributesPermissionsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateRolePermissionsDataAttributesPermissionsInner)

	if err != nil {
		return err
	}

	*o = UpdateRolePermissionsDataAttributesPermissionsInner(varUpdateRolePermissionsDataAttributesPermissionsInner)

	return err
}

type NullableUpdateRolePermissionsDataAttributesPermissionsInner struct {
	value *UpdateRolePermissionsDataAttributesPermissionsInner
	isSet bool
}

func (v NullableUpdateRolePermissionsDataAttributesPermissionsInner) Get() *UpdateRolePermissionsDataAttributesPermissionsInner {
	return v.value
}

func (v *NullableUpdateRolePermissionsDataAttributesPermissionsInner) Set(val *UpdateRolePermissionsDataAttributesPermissionsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateRolePermissionsDataAttributesPermissionsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateRolePermissionsDataAttributesPermissionsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateRolePermissionsDataAttributesPermissionsInner(val *UpdateRolePermissionsDataAttributesPermissionsInner) *NullableUpdateRolePermissionsDataAttributesPermissionsInner {
	return &NullableUpdateRolePermissionsDataAttributesPermissionsInner{value: val, isSet: true}
}

func (v NullableUpdateRolePermissionsDataAttributesPermissionsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateRolePermissionsDataAttributesPermissionsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


