/*
cities-svc API

API documentation for cities-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// checks if the UpdateMemberDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateMemberDataAttributes{}

// UpdateMemberDataAttributes struct for UpdateMemberDataAttributes
type UpdateMemberDataAttributes struct {
	// The position or role of the member within the agglomeration
	Position *string `json:"position,omitempty"`
	// A label or title associated with the member
	Label *string `json:"label,omitempty"`
}

// NewUpdateMemberDataAttributes instantiates a new UpdateMemberDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateMemberDataAttributes() *UpdateMemberDataAttributes {
	this := UpdateMemberDataAttributes{}
	return &this
}

// NewUpdateMemberDataAttributesWithDefaults instantiates a new UpdateMemberDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateMemberDataAttributesWithDefaults() *UpdateMemberDataAttributes {
	this := UpdateMemberDataAttributes{}
	return &this
}

// GetPosition returns the Position field value if set, zero value otherwise.
func (o *UpdateMemberDataAttributes) GetPosition() string {
	if o == nil || IsNil(o.Position) {
		var ret string
		return ret
	}
	return *o.Position
}

// GetPositionOk returns a tuple with the Position field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateMemberDataAttributes) GetPositionOk() (*string, bool) {
	if o == nil || IsNil(o.Position) {
		return nil, false
	}
	return o.Position, true
}

// HasPosition returns a boolean if a field has been set.
func (o *UpdateMemberDataAttributes) HasPosition() bool {
	if o != nil && !IsNil(o.Position) {
		return true
	}

	return false
}

// SetPosition gets a reference to the given string and assigns it to the Position field.
func (o *UpdateMemberDataAttributes) SetPosition(v string) {
	o.Position = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *UpdateMemberDataAttributes) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateMemberDataAttributes) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *UpdateMemberDataAttributes) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *UpdateMemberDataAttributes) SetLabel(v string) {
	o.Label = &v
}

func (o UpdateMemberDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateMemberDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Position) {
		toSerialize["position"] = o.Position
	}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	return toSerialize, nil
}

type NullableUpdateMemberDataAttributes struct {
	value *UpdateMemberDataAttributes
	isSet bool
}

func (v NullableUpdateMemberDataAttributes) Get() *UpdateMemberDataAttributes {
	return v.value
}

func (v *NullableUpdateMemberDataAttributes) Set(val *UpdateMemberDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateMemberDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateMemberDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateMemberDataAttributes(val *UpdateMemberDataAttributes) *NullableUpdateMemberDataAttributes {
	return &NullableUpdateMemberDataAttributes{value: val, isSet: true}
}

func (v NullableUpdateMemberDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateMemberDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


