/*
agglomerations-svc API

API documentation for agglomerations-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the AgglomerationDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgglomerationDataAttributes{}

// AgglomerationDataAttributes struct for AgglomerationDataAttributes
type AgglomerationDataAttributes struct {
	// The status of the agglomeration
	Status string `json:"status"`
	// The name of the agglomeration
	Name string `json:"name"`
	// The icon representing the agglomeration
	Icon string `json:"icon"`
	// The date and time when the agglomeration was created
	CreatedAt time.Time `json:"created_at"`
	// The date and time when the agglomeration was last updated
	UpdatedAt time.Time `json:"updated_at"`
}

type _AgglomerationDataAttributes AgglomerationDataAttributes

// NewAgglomerationDataAttributes instantiates a new AgglomerationDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgglomerationDataAttributes(status string, name string, icon string, createdAt time.Time, updatedAt time.Time) *AgglomerationDataAttributes {
	this := AgglomerationDataAttributes{}
	this.Status = status
	this.Name = name
	this.Icon = icon
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewAgglomerationDataAttributesWithDefaults instantiates a new AgglomerationDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgglomerationDataAttributesWithDefaults() *AgglomerationDataAttributes {
	this := AgglomerationDataAttributes{}
	return &this
}

// GetStatus returns the Status field value
func (o *AgglomerationDataAttributes) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *AgglomerationDataAttributes) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *AgglomerationDataAttributes) SetStatus(v string) {
	o.Status = v
}

// GetName returns the Name field value
func (o *AgglomerationDataAttributes) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AgglomerationDataAttributes) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AgglomerationDataAttributes) SetName(v string) {
	o.Name = v
}

// GetIcon returns the Icon field value
func (o *AgglomerationDataAttributes) GetIcon() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Icon
}

// GetIconOk returns a tuple with the Icon field value
// and a boolean to check if the value has been set.
func (o *AgglomerationDataAttributes) GetIconOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Icon, true
}

// SetIcon sets field value
func (o *AgglomerationDataAttributes) SetIcon(v string) {
	o.Icon = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *AgglomerationDataAttributes) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *AgglomerationDataAttributes) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *AgglomerationDataAttributes) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *AgglomerationDataAttributes) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *AgglomerationDataAttributes) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *AgglomerationDataAttributes) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o AgglomerationDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgglomerationDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["name"] = o.Name
	toSerialize["icon"] = o.Icon
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *AgglomerationDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"name",
		"icon",
		"created_at",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAgglomerationDataAttributes := _AgglomerationDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAgglomerationDataAttributes)

	if err != nil {
		return err
	}

	*o = AgglomerationDataAttributes(varAgglomerationDataAttributes)

	return err
}

type NullableAgglomerationDataAttributes struct {
	value *AgglomerationDataAttributes
	isSet bool
}

func (v NullableAgglomerationDataAttributes) Get() *AgglomerationDataAttributes {
	return v.value
}

func (v *NullableAgglomerationDataAttributes) Set(val *AgglomerationDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableAgglomerationDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableAgglomerationDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgglomerationDataAttributes(val *AgglomerationDataAttributes) *NullableAgglomerationDataAttributes {
	return &NullableAgglomerationDataAttributes{value: val, isSet: true}
}

func (v NullableAgglomerationDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgglomerationDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


