/*
organizations-svc API

API documentation for organizations-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MemberCollection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MemberCollection{}

// MemberCollection struct for MemberCollection
type MemberCollection struct {
	Data []MemberData `json:"data"`
	Links PaginationData `json:"links"`
}

type _MemberCollection MemberCollection

// NewMemberCollection instantiates a new MemberCollection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMemberCollection(data []MemberData, links PaginationData) *MemberCollection {
	this := MemberCollection{}
	this.Data = data
	this.Links = links
	return &this
}

// NewMemberCollectionWithDefaults instantiates a new MemberCollection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMemberCollectionWithDefaults() *MemberCollection {
	this := MemberCollection{}
	return &this
}

// GetData returns the Data field value
func (o *MemberCollection) GetData() []MemberData {
	if o == nil {
		var ret []MemberData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *MemberCollection) GetDataOk() ([]MemberData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *MemberCollection) SetData(v []MemberData) {
	o.Data = v
}

// GetLinks returns the Links field value
func (o *MemberCollection) GetLinks() PaginationData {
	if o == nil {
		var ret PaginationData
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *MemberCollection) GetLinksOk() (*PaginationData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *MemberCollection) SetLinks(v PaginationData) {
	o.Links = v
}

func (o MemberCollection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MemberCollection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["links"] = o.Links
	return toSerialize, nil
}

func (o *MemberCollection) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"links",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMemberCollection := _MemberCollection{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMemberCollection)

	if err != nil {
		return err
	}

	*o = MemberCollection(varMemberCollection)

	return err
}

type NullableMemberCollection struct {
	value *MemberCollection
	isSet bool
}

func (v NullableMemberCollection) Get() *MemberCollection {
	return v.value
}

func (v *NullableMemberCollection) Set(val *MemberCollection) {
	v.value = val
	v.isSet = true
}

func (v NullableMemberCollection) IsSet() bool {
	return v.isSet
}

func (v *NullableMemberCollection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMemberCollection(val *MemberCollection) *NullableMemberCollection {
	return &NullableMemberCollection{value: val, isSet: true}
}

func (v NullableMemberCollection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMemberCollection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


