/*
organizations-svc API

API documentation for organizations-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"github.com/google/uuid"
	"bytes"
	"fmt"
)

// checks if the UpdateOrganizationLinksData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateOrganizationLinksData{}

// UpdateOrganizationLinksData struct for UpdateOrganizationLinksData
type UpdateOrganizationLinksData struct {
	// Upload session id
	Id uuid.UUID `json:"id"`
	Type string `json:"type"`
	Attributes UpdateOrganizationLinksDataAttributes `json:"attributes"`
	Relationships UpdateOrganizationLinksDataRelationships `json:"relationships"`
}

type _UpdateOrganizationLinksData UpdateOrganizationLinksData

// NewUpdateOrganizationLinksData instantiates a new UpdateOrganizationLinksData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateOrganizationLinksData(id uuid.UUID, type_ string, attributes UpdateOrganizationLinksDataAttributes, relationships UpdateOrganizationLinksDataRelationships) *UpdateOrganizationLinksData {
	this := UpdateOrganizationLinksData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	this.Relationships = relationships
	return &this
}

// NewUpdateOrganizationLinksDataWithDefaults instantiates a new UpdateOrganizationLinksData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateOrganizationLinksDataWithDefaults() *UpdateOrganizationLinksData {
	this := UpdateOrganizationLinksData{}
	return &this
}

// GetId returns the Id field value
func (o *UpdateOrganizationLinksData) GetId() uuid.UUID {
	if o == nil {
		var ret uuid.UUID
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UpdateOrganizationLinksData) GetIdOk() (*uuid.UUID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UpdateOrganizationLinksData) SetId(v uuid.UUID) {
	o.Id = v
}

// GetType returns the Type field value
func (o *UpdateOrganizationLinksData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *UpdateOrganizationLinksData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *UpdateOrganizationLinksData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *UpdateOrganizationLinksData) GetAttributes() UpdateOrganizationLinksDataAttributes {
	if o == nil {
		var ret UpdateOrganizationLinksDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *UpdateOrganizationLinksData) GetAttributesOk() (*UpdateOrganizationLinksDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *UpdateOrganizationLinksData) SetAttributes(v UpdateOrganizationLinksDataAttributes) {
	o.Attributes = v
}

// GetRelationships returns the Relationships field value
func (o *UpdateOrganizationLinksData) GetRelationships() UpdateOrganizationLinksDataRelationships {
	if o == nil {
		var ret UpdateOrganizationLinksDataRelationships
		return ret
	}

	return o.Relationships
}

// GetRelationshipsOk returns a tuple with the Relationships field value
// and a boolean to check if the value has been set.
func (o *UpdateOrganizationLinksData) GetRelationshipsOk() (*UpdateOrganizationLinksDataRelationships, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Relationships, true
}

// SetRelationships sets field value
func (o *UpdateOrganizationLinksData) SetRelationships(v UpdateOrganizationLinksDataRelationships) {
	o.Relationships = v
}

func (o UpdateOrganizationLinksData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateOrganizationLinksData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	toSerialize["relationships"] = o.Relationships
	return toSerialize, nil
}

func (o *UpdateOrganizationLinksData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
		"relationships",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateOrganizationLinksData := _UpdateOrganizationLinksData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateOrganizationLinksData)

	if err != nil {
		return err
	}

	*o = UpdateOrganizationLinksData(varUpdateOrganizationLinksData)

	return err
}

type NullableUpdateOrganizationLinksData struct {
	value *UpdateOrganizationLinksData
	isSet bool
}

func (v NullableUpdateOrganizationLinksData) Get() *UpdateOrganizationLinksData {
	return v.value
}

func (v *NullableUpdateOrganizationLinksData) Set(val *UpdateOrganizationLinksData) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateOrganizationLinksData) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateOrganizationLinksData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateOrganizationLinksData(val *UpdateOrganizationLinksData) *NullableUpdateOrganizationLinksData {
	return &NullableUpdateOrganizationLinksData{value: val, isSet: true}
}

func (v NullableUpdateOrganizationLinksData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateOrganizationLinksData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


