/*
organizations-svc API

API documentation for organizations-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"github.com/google/uuid"
	"bytes"
	"fmt"
)

// checks if the CreateInviteDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateInviteDataAttributes{}

// CreateInviteDataAttributes struct for CreateInviteDataAttributes
type CreateInviteDataAttributes struct {
	// The ID of the organization to which the invite belongs
	OrganizationId uuid.UUID `json:"organization_id"`
	// The ID of the account that was invited
	AccountId uuid.UUID `json:"account_id"`
}

type _CreateInviteDataAttributes CreateInviteDataAttributes

// NewCreateInviteDataAttributes instantiates a new CreateInviteDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateInviteDataAttributes(organizationId uuid.UUID, accountId uuid.UUID) *CreateInviteDataAttributes {
	this := CreateInviteDataAttributes{}
	this.OrganizationId = organizationId
	this.AccountId = accountId
	return &this
}

// NewCreateInviteDataAttributesWithDefaults instantiates a new CreateInviteDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateInviteDataAttributesWithDefaults() *CreateInviteDataAttributes {
	this := CreateInviteDataAttributes{}
	return &this
}

// GetOrganizationId returns the OrganizationId field value
func (o *CreateInviteDataAttributes) GetOrganizationId() uuid.UUID {
	if o == nil {
		var ret uuid.UUID
		return ret
	}

	return o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value
// and a boolean to check if the value has been set.
func (o *CreateInviteDataAttributes) GetOrganizationIdOk() (*uuid.UUID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrganizationId, true
}

// SetOrganizationId sets field value
func (o *CreateInviteDataAttributes) SetOrganizationId(v uuid.UUID) {
	o.OrganizationId = v
}

// GetAccountId returns the AccountId field value
func (o *CreateInviteDataAttributes) GetAccountId() uuid.UUID {
	if o == nil {
		var ret uuid.UUID
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *CreateInviteDataAttributes) GetAccountIdOk() (*uuid.UUID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *CreateInviteDataAttributes) SetAccountId(v uuid.UUID) {
	o.AccountId = v
}

func (o CreateInviteDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateInviteDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["organization_id"] = o.OrganizationId
	toSerialize["account_id"] = o.AccountId
	return toSerialize, nil
}

func (o *CreateInviteDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"organization_id",
		"account_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateInviteDataAttributes := _CreateInviteDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateInviteDataAttributes)

	if err != nil {
		return err
	}

	*o = CreateInviteDataAttributes(varCreateInviteDataAttributes)

	return err
}

type NullableCreateInviteDataAttributes struct {
	value *CreateInviteDataAttributes
	isSet bool
}

func (v NullableCreateInviteDataAttributes) Get() *CreateInviteDataAttributes {
	return v.value
}

func (v *NullableCreateInviteDataAttributes) Set(val *CreateInviteDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateInviteDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateInviteDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateInviteDataAttributes(val *CreateInviteDataAttributes) *NullableCreateInviteDataAttributes {
	return &NullableCreateInviteDataAttributes{value: val, isSet: true}
}

func (v NullableCreateInviteDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateInviteDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


