/*
agglomerations-svc API

API documentation for agglomerations-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"github.com/google/uuid"
	"bytes"
	"fmt"
)

// checks if the CreateRoleDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateRoleDataAttributes{}

// CreateRoleDataAttributes struct for CreateRoleDataAttributes
type CreateRoleDataAttributes struct {
	// The ID of the agglomeration this role belongs to
	AgglomerationId uuid.UUID `json:"agglomeration_id"`
	// The rank of the role within the agglomeration
	Rank uint `json:"rank"`
	// The name of the role
	Name string `json:"name"`
	// A brief description of the role
	Description string `json:"description"`
	// The color associated with the role in HEX format
	Color string `json:"color"`
}

type _CreateRoleDataAttributes CreateRoleDataAttributes

// NewCreateRoleDataAttributes instantiates a new CreateRoleDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateRoleDataAttributes(agglomerationId uuid.UUID, rank uint, name string, description string, color string) *CreateRoleDataAttributes {
	this := CreateRoleDataAttributes{}
	this.AgglomerationId = agglomerationId
	this.Rank = rank
	this.Name = name
	this.Description = description
	this.Color = color
	return &this
}

// NewCreateRoleDataAttributesWithDefaults instantiates a new CreateRoleDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateRoleDataAttributesWithDefaults() *CreateRoleDataAttributes {
	this := CreateRoleDataAttributes{}
	return &this
}

// GetAgglomerationId returns the AgglomerationId field value
func (o *CreateRoleDataAttributes) GetAgglomerationId() uuid.UUID {
	if o == nil {
		var ret uuid.UUID
		return ret
	}

	return o.AgglomerationId
}

// GetAgglomerationIdOk returns a tuple with the AgglomerationId field value
// and a boolean to check if the value has been set.
func (o *CreateRoleDataAttributes) GetAgglomerationIdOk() (*uuid.UUID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgglomerationId, true
}

// SetAgglomerationId sets field value
func (o *CreateRoleDataAttributes) SetAgglomerationId(v uuid.UUID) {
	o.AgglomerationId = v
}

// GetRank returns the Rank field value
func (o *CreateRoleDataAttributes) GetRank() uint {
	if o == nil {
		var ret uint
		return ret
	}

	return o.Rank
}

// GetRankOk returns a tuple with the Rank field value
// and a boolean to check if the value has been set.
func (o *CreateRoleDataAttributes) GetRankOk() (*uint, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Rank, true
}

// SetRank sets field value
func (o *CreateRoleDataAttributes) SetRank(v uint) {
	o.Rank = v
}

// GetName returns the Name field value
func (o *CreateRoleDataAttributes) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateRoleDataAttributes) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateRoleDataAttributes) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
func (o *CreateRoleDataAttributes) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *CreateRoleDataAttributes) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *CreateRoleDataAttributes) SetDescription(v string) {
	o.Description = v
}

// GetColor returns the Color field value
func (o *CreateRoleDataAttributes) GetColor() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Color
}

// GetColorOk returns a tuple with the Color field value
// and a boolean to check if the value has been set.
func (o *CreateRoleDataAttributes) GetColorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Color, true
}

// SetColor sets field value
func (o *CreateRoleDataAttributes) SetColor(v string) {
	o.Color = v
}

func (o CreateRoleDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateRoleDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["agglomeration_id"] = o.AgglomerationId
	toSerialize["rank"] = o.Rank
	toSerialize["name"] = o.Name
	toSerialize["description"] = o.Description
	toSerialize["color"] = o.Color
	return toSerialize, nil
}

func (o *CreateRoleDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"agglomeration_id",
		"rank",
		"name",
		"description",
		"color",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateRoleDataAttributes := _CreateRoleDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateRoleDataAttributes)

	if err != nil {
		return err
	}

	*o = CreateRoleDataAttributes(varCreateRoleDataAttributes)

	return err
}

type NullableCreateRoleDataAttributes struct {
	value *CreateRoleDataAttributes
	isSet bool
}

func (v NullableCreateRoleDataAttributes) Get() *CreateRoleDataAttributes {
	return v.value
}

func (v *NullableCreateRoleDataAttributes) Set(val *CreateRoleDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateRoleDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateRoleDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateRoleDataAttributes(val *CreateRoleDataAttributes) *NullableCreateRoleDataAttributes {
	return &NullableCreateRoleDataAttributes{value: val, isSet: true}
}

func (v NullableCreateRoleDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateRoleDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


