/*
organizations-svc API

API documentation for organizations-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateOrganizationDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateOrganizationDataAttributes{}

// CreateOrganizationDataAttributes struct for CreateOrganizationDataAttributes
type CreateOrganizationDataAttributes struct {
	// The name of the organization
	Name string `json:"name"`
	// The icon representing the organization
	Icon *string `json:"icon,omitempty"`
}

type _CreateOrganizationDataAttributes CreateOrganizationDataAttributes

// NewCreateOrganizationDataAttributes instantiates a new CreateOrganizationDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOrganizationDataAttributes(name string) *CreateOrganizationDataAttributes {
	this := CreateOrganizationDataAttributes{}
	this.Name = name
	return &this
}

// NewCreateOrganizationDataAttributesWithDefaults instantiates a new CreateOrganizationDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOrganizationDataAttributesWithDefaults() *CreateOrganizationDataAttributes {
	this := CreateOrganizationDataAttributes{}
	return &this
}

// GetName returns the Name field value
func (o *CreateOrganizationDataAttributes) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateOrganizationDataAttributes) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateOrganizationDataAttributes) SetName(v string) {
	o.Name = v
}

// GetIcon returns the Icon field value if set, zero value otherwise.
func (o *CreateOrganizationDataAttributes) GetIcon() string {
	if o == nil || IsNil(o.Icon) {
		var ret string
		return ret
	}
	return *o.Icon
}

// GetIconOk returns a tuple with the Icon field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrganizationDataAttributes) GetIconOk() (*string, bool) {
	if o == nil || IsNil(o.Icon) {
		return nil, false
	}
	return o.Icon, true
}

// HasIcon returns a boolean if a field has been set.
func (o *CreateOrganizationDataAttributes) HasIcon() bool {
	if o != nil && !IsNil(o.Icon) {
		return true
	}

	return false
}

// SetIcon gets a reference to the given string and assigns it to the Icon field.
func (o *CreateOrganizationDataAttributes) SetIcon(v string) {
	o.Icon = &v
}

func (o CreateOrganizationDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateOrganizationDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Icon) {
		toSerialize["icon"] = o.Icon
	}
	return toSerialize, nil
}

func (o *CreateOrganizationDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateOrganizationDataAttributes := _CreateOrganizationDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateOrganizationDataAttributes)

	if err != nil {
		return err
	}

	*o = CreateOrganizationDataAttributes(varCreateOrganizationDataAttributes)

	return err
}

type NullableCreateOrganizationDataAttributes struct {
	value *CreateOrganizationDataAttributes
	isSet bool
}

func (v NullableCreateOrganizationDataAttributes) Get() *CreateOrganizationDataAttributes {
	return v.value
}

func (v *NullableCreateOrganizationDataAttributes) Set(val *CreateOrganizationDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOrganizationDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOrganizationDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOrganizationDataAttributes(val *CreateOrganizationDataAttributes) *NullableCreateOrganizationDataAttributes {
	return &NullableCreateOrganizationDataAttributes{value: val, isSet: true}
}

func (v NullableCreateOrganizationDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOrganizationDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


