/*
agglomerations-svc API

API documentation for agglomerations-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// checks if the RoleDataRelationships type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RoleDataRelationships{}

// RoleDataRelationships struct for RoleDataRelationships
type RoleDataRelationships struct {
	Permissions []RolePermission `json:"permissions,omitempty"`
}

// NewRoleDataRelationships instantiates a new RoleDataRelationships object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoleDataRelationships() *RoleDataRelationships {
	this := RoleDataRelationships{}
	return &this
}

// NewRoleDataRelationshipsWithDefaults instantiates a new RoleDataRelationships object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRoleDataRelationshipsWithDefaults() *RoleDataRelationships {
	this := RoleDataRelationships{}
	return &this
}

// GetPermissions returns the Permissions field value if set, zero value otherwise.
func (o *RoleDataRelationships) GetPermissions() []RolePermission {
	if o == nil || IsNil(o.Permissions) {
		var ret []RolePermission
		return ret
	}
	return o.Permissions
}

// GetPermissionsOk returns a tuple with the Permissions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoleDataRelationships) GetPermissionsOk() ([]RolePermission, bool) {
	if o == nil || IsNil(o.Permissions) {
		return nil, false
	}
	return o.Permissions, true
}

// HasPermissions returns a boolean if a field has been set.
func (o *RoleDataRelationships) HasPermissions() bool {
	if o != nil && !IsNil(o.Permissions) {
		return true
	}

	return false
}

// SetPermissions gets a reference to the given []RolePermission and assigns it to the Permissions field.
func (o *RoleDataRelationships) SetPermissions(v []RolePermission) {
	o.Permissions = v
}

func (o RoleDataRelationships) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RoleDataRelationships) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Permissions) {
		toSerialize["permissions"] = o.Permissions
	}
	return toSerialize, nil
}

type NullableRoleDataRelationships struct {
	value *RoleDataRelationships
	isSet bool
}

func (v NullableRoleDataRelationships) Get() *RoleDataRelationships {
	return v.value
}

func (v *NullableRoleDataRelationships) Set(val *RoleDataRelationships) {
	v.value = val
	v.isSet = true
}

func (v NullableRoleDataRelationships) IsSet() bool {
	return v.isSet
}

func (v *NullableRoleDataRelationships) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoleDataRelationships(val *RoleDataRelationships) *NullableRoleDataRelationships {
	return &NullableRoleDataRelationships{value: val, isSet: true}
}

func (v NullableRoleDataRelationships) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoleDataRelationships) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


