/*
organizations-svc API

API documentation for organizations-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateInvite type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateInvite{}

// CreateInvite struct for CreateInvite
type CreateInvite struct {
	Data CreateInviteData `json:"data"`
}

type _CreateInvite CreateInvite

// NewCreateInvite instantiates a new CreateInvite object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateInvite(data CreateInviteData) *CreateInvite {
	this := CreateInvite{}
	this.Data = data
	return &this
}

// NewCreateInviteWithDefaults instantiates a new CreateInvite object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateInviteWithDefaults() *CreateInvite {
	this := CreateInvite{}
	return &this
}

// GetData returns the Data field value
func (o *CreateInvite) GetData() CreateInviteData {
	if o == nil {
		var ret CreateInviteData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CreateInvite) GetDataOk() (*CreateInviteData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *CreateInvite) SetData(v CreateInviteData) {
	o.Data = v
}

func (o CreateInvite) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateInvite) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *CreateInvite) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateInvite := _CreateInvite{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateInvite)

	if err != nil {
		return err
	}

	*o = CreateInvite(varCreateInvite)

	return err
}

type NullableCreateInvite struct {
	value *CreateInvite
	isSet bool
}

func (v NullableCreateInvite) Get() *CreateInvite {
	return v.value
}

func (v *NullableCreateInvite) Set(val *CreateInvite) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateInvite) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateInvite) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateInvite(val *CreateInvite) *NullableCreateInvite {
	return &NullableCreateInvite{value: val, isSet: true}
}

func (v NullableCreateInvite) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateInvite) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


