/*
agglomerations-svc API

API documentation for agglomerations-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"github.com/google/uuid"
	"bytes"
	"fmt"
)

// checks if the SentInviteDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SentInviteDataAttributes{}

// SentInviteDataAttributes struct for SentInviteDataAttributes
type SentInviteDataAttributes struct {
	// The ID of the agglomeration to which the invite belongs
	AgglomerationId uuid.UUID `json:"agglomeration_id"`
	// The ID of the account that was invited
	AccountId uuid.UUID `json:"account_id"`
}

type _SentInviteDataAttributes SentInviteDataAttributes

// NewSentInviteDataAttributes instantiates a new SentInviteDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSentInviteDataAttributes(agglomerationId uuid.UUID, accountId uuid.UUID) *SentInviteDataAttributes {
	this := SentInviteDataAttributes{}
	this.AgglomerationId = agglomerationId
	this.AccountId = accountId
	return &this
}

// NewSentInviteDataAttributesWithDefaults instantiates a new SentInviteDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSentInviteDataAttributesWithDefaults() *SentInviteDataAttributes {
	this := SentInviteDataAttributes{}
	return &this
}

// GetAgglomerationId returns the AgglomerationId field value
func (o *SentInviteDataAttributes) GetAgglomerationId() uuid.UUID {
	if o == nil {
		var ret uuid.UUID
		return ret
	}

	return o.AgglomerationId
}

// GetAgglomerationIdOk returns a tuple with the AgglomerationId field value
// and a boolean to check if the value has been set.
func (o *SentInviteDataAttributes) GetAgglomerationIdOk() (*uuid.UUID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgglomerationId, true
}

// SetAgglomerationId sets field value
func (o *SentInviteDataAttributes) SetAgglomerationId(v uuid.UUID) {
	o.AgglomerationId = v
}

// GetAccountId returns the AccountId field value
func (o *SentInviteDataAttributes) GetAccountId() uuid.UUID {
	if o == nil {
		var ret uuid.UUID
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *SentInviteDataAttributes) GetAccountIdOk() (*uuid.UUID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *SentInviteDataAttributes) SetAccountId(v uuid.UUID) {
	o.AccountId = v
}

func (o SentInviteDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SentInviteDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["agglomeration_id"] = o.AgglomerationId
	toSerialize["account_id"] = o.AccountId
	return toSerialize, nil
}

func (o *SentInviteDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"agglomeration_id",
		"account_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSentInviteDataAttributes := _SentInviteDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSentInviteDataAttributes)

	if err != nil {
		return err
	}

	*o = SentInviteDataAttributes(varSentInviteDataAttributes)

	return err
}

type NullableSentInviteDataAttributes struct {
	value *SentInviteDataAttributes
	isSet bool
}

func (v NullableSentInviteDataAttributes) Get() *SentInviteDataAttributes {
	return v.value
}

func (v *NullableSentInviteDataAttributes) Set(val *SentInviteDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableSentInviteDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableSentInviteDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSentInviteDataAttributes(val *SentInviteDataAttributes) *NullableSentInviteDataAttributes {
	return &NullableSentInviteDataAttributes{value: val, isSet: true}
}

func (v NullableSentInviteDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSentInviteDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


