/*
organizations-svc API

API documentation for organizations-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OrganizationsCollection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizationsCollection{}

// OrganizationsCollection struct for OrganizationsCollection
type OrganizationsCollection struct {
	Data []OrganizationData `json:"data"`
	Links PaginationData `json:"links"`
}

type _OrganizationsCollection OrganizationsCollection

// NewOrganizationsCollection instantiates a new OrganizationsCollection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationsCollection(data []OrganizationData, links PaginationData) *OrganizationsCollection {
	this := OrganizationsCollection{}
	this.Data = data
	this.Links = links
	return &this
}

// NewOrganizationsCollectionWithDefaults instantiates a new OrganizationsCollection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationsCollectionWithDefaults() *OrganizationsCollection {
	this := OrganizationsCollection{}
	return &this
}

// GetData returns the Data field value
func (o *OrganizationsCollection) GetData() []OrganizationData {
	if o == nil {
		var ret []OrganizationData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *OrganizationsCollection) GetDataOk() ([]OrganizationData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *OrganizationsCollection) SetData(v []OrganizationData) {
	o.Data = v
}

// GetLinks returns the Links field value
func (o *OrganizationsCollection) GetLinks() PaginationData {
	if o == nil {
		var ret PaginationData
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *OrganizationsCollection) GetLinksOk() (*PaginationData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *OrganizationsCollection) SetLinks(v PaginationData) {
	o.Links = v
}

func (o OrganizationsCollection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizationsCollection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["links"] = o.Links
	return toSerialize, nil
}

func (o *OrganizationsCollection) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"links",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrganizationsCollection := _OrganizationsCollection{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOrganizationsCollection)

	if err != nil {
		return err
	}

	*o = OrganizationsCollection(varOrganizationsCollection)

	return err
}

type NullableOrganizationsCollection struct {
	value *OrganizationsCollection
	isSet bool
}

func (v NullableOrganizationsCollection) Get() *OrganizationsCollection {
	return v.value
}

func (v *NullableOrganizationsCollection) Set(val *OrganizationsCollection) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationsCollection) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationsCollection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationsCollection(val *OrganizationsCollection) *NullableOrganizationsCollection {
	return &NullableOrganizationsCollection{value: val, isSet: true}
}

func (v NullableOrganizationsCollection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationsCollection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


