/*
agglomerations-svc API

API documentation for agglomerations-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Agglomeration type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Agglomeration{}

// Agglomeration struct for Agglomeration
type Agglomeration struct {
	Data AgglomerationData `json:"data"`
}

type _Agglomeration Agglomeration

// NewAgglomeration instantiates a new Agglomeration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgglomeration(data AgglomerationData) *Agglomeration {
	this := Agglomeration{}
	this.Data = data
	return &this
}

// NewAgglomerationWithDefaults instantiates a new Agglomeration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgglomerationWithDefaults() *Agglomeration {
	this := Agglomeration{}
	return &this
}

// GetData returns the Data field value
func (o *Agglomeration) GetData() AgglomerationData {
	if o == nil {
		var ret AgglomerationData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *Agglomeration) GetDataOk() (*AgglomerationData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *Agglomeration) SetData(v AgglomerationData) {
	o.Data = v
}

func (o Agglomeration) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Agglomeration) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *Agglomeration) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAgglomeration := _Agglomeration{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAgglomeration)

	if err != nil {
		return err
	}

	*o = Agglomeration(varAgglomeration)

	return err
}

type NullableAgglomeration struct {
	value *Agglomeration
	isSet bool
}

func (v NullableAgglomeration) Get() *Agglomeration {
	return v.value
}

func (v *NullableAgglomeration) Set(val *Agglomeration) {
	v.value = val
	v.isSet = true
}

func (v NullableAgglomeration) IsSet() bool {
	return v.isSet
}

func (v *NullableAgglomeration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgglomeration(val *Agglomeration) *NullableAgglomeration {
	return &NullableAgglomeration{value: val, isSet: true}
}

func (v NullableAgglomeration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgglomeration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


