/*
cities-svc API

API documentation for cities-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"github.com/google/uuid"
	"time"
	"bytes"
	"fmt"
)

// checks if the RoleDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RoleDataAttributes{}

// RoleDataAttributes struct for RoleDataAttributes
type RoleDataAttributes struct {
	// The ID of the agglomeration this role belongs to
	AgglomerationId uuid.UUID `json:"agglomeration_id"`
	// Indicates if this role is the head role of the agglomeration
	Head bool `json:"head"`
	// The rank of the role within the agglomeration
	Rank int32 `json:"rank"`
	// The name of the role
	Name string `json:"name"`
	// A brief description of the role
	Description string `json:"description"`
	// The color associated with the role in HEX format
	Color string `json:"color"`
	// Timestamp when the role was created
	CreatedAt time.Time `json:"created_at"`
	// Timestamp when the role was last updated
	UpdatedAt time.Time `json:"updated_at"`
}

type _RoleDataAttributes RoleDataAttributes

// NewRoleDataAttributes instantiates a new RoleDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoleDataAttributes(agglomerationId uuid.UUID, head bool, rank int32, name string, description string, color string, createdAt time.Time, updatedAt time.Time) *RoleDataAttributes {
	this := RoleDataAttributes{}
	this.AgglomerationId = agglomerationId
	this.Head = head
	this.Rank = rank
	this.Name = name
	this.Description = description
	this.Color = color
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewRoleDataAttributesWithDefaults instantiates a new RoleDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRoleDataAttributesWithDefaults() *RoleDataAttributes {
	this := RoleDataAttributes{}
	return &this
}

// GetAgglomerationId returns the AgglomerationId field value
func (o *RoleDataAttributes) GetAgglomerationId() uuid.UUID {
	if o == nil {
		var ret uuid.UUID
		return ret
	}

	return o.AgglomerationId
}

// GetAgglomerationIdOk returns a tuple with the AgglomerationId field value
// and a boolean to check if the value has been set.
func (o *RoleDataAttributes) GetAgglomerationIdOk() (*uuid.UUID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgglomerationId, true
}

// SetAgglomerationId sets field value
func (o *RoleDataAttributes) SetAgglomerationId(v uuid.UUID) {
	o.AgglomerationId = v
}

// GetHead returns the Head field value
func (o *RoleDataAttributes) GetHead() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Head
}

// GetHeadOk returns a tuple with the Head field value
// and a boolean to check if the value has been set.
func (o *RoleDataAttributes) GetHeadOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Head, true
}

// SetHead sets field value
func (o *RoleDataAttributes) SetHead(v bool) {
	o.Head = v
}

// GetRank returns the Rank field value
func (o *RoleDataAttributes) GetRank() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Rank
}

// GetRankOk returns a tuple with the Rank field value
// and a boolean to check if the value has been set.
func (o *RoleDataAttributes) GetRankOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Rank, true
}

// SetRank sets field value
func (o *RoleDataAttributes) SetRank(v int32) {
	o.Rank = v
}

// GetName returns the Name field value
func (o *RoleDataAttributes) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *RoleDataAttributes) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *RoleDataAttributes) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
func (o *RoleDataAttributes) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *RoleDataAttributes) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *RoleDataAttributes) SetDescription(v string) {
	o.Description = v
}

// GetColor returns the Color field value
func (o *RoleDataAttributes) GetColor() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Color
}

// GetColorOk returns a tuple with the Color field value
// and a boolean to check if the value has been set.
func (o *RoleDataAttributes) GetColorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Color, true
}

// SetColor sets field value
func (o *RoleDataAttributes) SetColor(v string) {
	o.Color = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *RoleDataAttributes) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *RoleDataAttributes) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *RoleDataAttributes) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *RoleDataAttributes) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *RoleDataAttributes) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *RoleDataAttributes) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o RoleDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RoleDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["agglomeration_id"] = o.AgglomerationId
	toSerialize["head"] = o.Head
	toSerialize["rank"] = o.Rank
	toSerialize["name"] = o.Name
	toSerialize["description"] = o.Description
	toSerialize["color"] = o.Color
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *RoleDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"agglomeration_id",
		"head",
		"rank",
		"name",
		"description",
		"color",
		"created_at",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRoleDataAttributes := _RoleDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRoleDataAttributes)

	if err != nil {
		return err
	}

	*o = RoleDataAttributes(varRoleDataAttributes)

	return err
}

type NullableRoleDataAttributes struct {
	value *RoleDataAttributes
	isSet bool
}

func (v NullableRoleDataAttributes) Get() *RoleDataAttributes {
	return v.value
}

func (v *NullableRoleDataAttributes) Set(val *RoleDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableRoleDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableRoleDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoleDataAttributes(val *RoleDataAttributes) *NullableRoleDataAttributes {
	return &NullableRoleDataAttributes{value: val, isSet: true}
}

func (v NullableRoleDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoleDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


