/*
cities-svc API

API documentation for cities-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateAgglomeration type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAgglomeration{}

// CreateAgglomeration struct for CreateAgglomeration
type CreateAgglomeration struct {
	Data CreateAgglomerationData `json:"data"`
}

type _CreateAgglomeration CreateAgglomeration

// NewCreateAgglomeration instantiates a new CreateAgglomeration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAgglomeration(data CreateAgglomerationData) *CreateAgglomeration {
	this := CreateAgglomeration{}
	this.Data = data
	return &this
}

// NewCreateAgglomerationWithDefaults instantiates a new CreateAgglomeration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAgglomerationWithDefaults() *CreateAgglomeration {
	this := CreateAgglomeration{}
	return &this
}

// GetData returns the Data field value
func (o *CreateAgglomeration) GetData() CreateAgglomerationData {
	if o == nil {
		var ret CreateAgglomerationData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CreateAgglomeration) GetDataOk() (*CreateAgglomerationData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *CreateAgglomeration) SetData(v CreateAgglomerationData) {
	o.Data = v
}

func (o CreateAgglomeration) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAgglomeration) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *CreateAgglomeration) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateAgglomeration := _CreateAgglomeration{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateAgglomeration)

	if err != nil {
		return err
	}

	*o = CreateAgglomeration(varCreateAgglomeration)

	return err
}

type NullableCreateAgglomeration struct {
	value *CreateAgglomeration
	isSet bool
}

func (v NullableCreateAgglomeration) Get() *CreateAgglomeration {
	return v.value
}

func (v *NullableCreateAgglomeration) Set(val *CreateAgglomeration) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAgglomeration) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAgglomeration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAgglomeration(val *CreateAgglomeration) *NullableCreateAgglomeration {
	return &NullableCreateAgglomeration{value: val, isSet: true}
}

func (v NullableCreateAgglomeration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAgglomeration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


