/*
organizations-svc API

API documentation for organizations-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateRoleData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateRoleData{}

// CreateRoleData struct for CreateRoleData
type CreateRoleData struct {
	Type string `json:"type"`
	Attributes CreateRoleDataAttributes `json:"attributes"`
}

type _CreateRoleData CreateRoleData

// NewCreateRoleData instantiates a new CreateRoleData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateRoleData(type_ string, attributes CreateRoleDataAttributes) *CreateRoleData {
	this := CreateRoleData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewCreateRoleDataWithDefaults instantiates a new CreateRoleData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateRoleDataWithDefaults() *CreateRoleData {
	this := CreateRoleData{}
	return &this
}

// GetType returns the Type field value
func (o *CreateRoleData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CreateRoleData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CreateRoleData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *CreateRoleData) GetAttributes() CreateRoleDataAttributes {
	if o == nil {
		var ret CreateRoleDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *CreateRoleData) GetAttributesOk() (*CreateRoleDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *CreateRoleData) SetAttributes(v CreateRoleDataAttributes) {
	o.Attributes = v
}

func (o CreateRoleData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateRoleData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *CreateRoleData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateRoleData := _CreateRoleData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateRoleData)

	if err != nil {
		return err
	}

	*o = CreateRoleData(varCreateRoleData)

	return err
}

type NullableCreateRoleData struct {
	value *CreateRoleData
	isSet bool
}

func (v NullableCreateRoleData) Get() *CreateRoleData {
	return v.value
}

func (v *NullableCreateRoleData) Set(val *CreateRoleData) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateRoleData) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateRoleData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateRoleData(val *CreateRoleData) *NullableCreateRoleData {
	return &NullableCreateRoleData{value: val, isSet: true}
}

func (v NullableCreateRoleData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateRoleData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


