/*
organizations-svc API

API documentation for organizations-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateOrganizationLinks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateOrganizationLinks{}

// UpdateOrganizationLinks struct for UpdateOrganizationLinks
type UpdateOrganizationLinks struct {
	Data UpdateOrganizationLinksData `json:"data"`
	Included []OrganizationData `json:"included"`
}

type _UpdateOrganizationLinks UpdateOrganizationLinks

// NewUpdateOrganizationLinks instantiates a new UpdateOrganizationLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateOrganizationLinks(data UpdateOrganizationLinksData, included []OrganizationData) *UpdateOrganizationLinks {
	this := UpdateOrganizationLinks{}
	this.Data = data
	this.Included = included
	return &this
}

// NewUpdateOrganizationLinksWithDefaults instantiates a new UpdateOrganizationLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateOrganizationLinksWithDefaults() *UpdateOrganizationLinks {
	this := UpdateOrganizationLinks{}
	return &this
}

// GetData returns the Data field value
func (o *UpdateOrganizationLinks) GetData() UpdateOrganizationLinksData {
	if o == nil {
		var ret UpdateOrganizationLinksData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UpdateOrganizationLinks) GetDataOk() (*UpdateOrganizationLinksData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *UpdateOrganizationLinks) SetData(v UpdateOrganizationLinksData) {
	o.Data = v
}

// GetIncluded returns the Included field value
func (o *UpdateOrganizationLinks) GetIncluded() []OrganizationData {
	if o == nil {
		var ret []OrganizationData
		return ret
	}

	return o.Included
}

// GetIncludedOk returns a tuple with the Included field value
// and a boolean to check if the value has been set.
func (o *UpdateOrganizationLinks) GetIncludedOk() ([]OrganizationData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Included, true
}

// SetIncluded sets field value
func (o *UpdateOrganizationLinks) SetIncluded(v []OrganizationData) {
	o.Included = v
}

func (o UpdateOrganizationLinks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateOrganizationLinks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["included"] = o.Included
	return toSerialize, nil
}

func (o *UpdateOrganizationLinks) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"included",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateOrganizationLinks := _UpdateOrganizationLinks{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateOrganizationLinks)

	if err != nil {
		return err
	}

	*o = UpdateOrganizationLinks(varUpdateOrganizationLinks)

	return err
}

type NullableUpdateOrganizationLinks struct {
	value *UpdateOrganizationLinks
	isSet bool
}

func (v NullableUpdateOrganizationLinks) Get() *UpdateOrganizationLinks {
	return v.value
}

func (v *NullableUpdateOrganizationLinks) Set(val *UpdateOrganizationLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateOrganizationLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateOrganizationLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateOrganizationLinks(val *UpdateOrganizationLinks) *NullableUpdateOrganizationLinks {
	return &NullableUpdateOrganizationLinks{value: val, isSet: true}
}

func (v NullableUpdateOrganizationLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateOrganizationLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


