/*
agglomerations-svc API

API documentation for agglomerations-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"github.com/google/uuid"
	"bytes"
	"fmt"
)

// checks if the CreateAgglomerationDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAgglomerationDataAttributes{}

// CreateAgglomerationDataAttributes struct for CreateAgglomerationDataAttributes
type CreateAgglomerationDataAttributes struct {
	// Account ID of the head of the agglomeration
	Head uuid.UUID `json:"head"`
	// The name of the agglomeration
	Name string `json:"name"`
	// The icon representing the agglomeration
	Icon *string `json:"icon,omitempty"`
}

type _CreateAgglomerationDataAttributes CreateAgglomerationDataAttributes

// NewCreateAgglomerationDataAttributes instantiates a new CreateAgglomerationDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAgglomerationDataAttributes(head uuid.UUID, name string) *CreateAgglomerationDataAttributes {
	this := CreateAgglomerationDataAttributes{}
	this.Head = head
	this.Name = name
	return &this
}

// NewCreateAgglomerationDataAttributesWithDefaults instantiates a new CreateAgglomerationDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAgglomerationDataAttributesWithDefaults() *CreateAgglomerationDataAttributes {
	this := CreateAgglomerationDataAttributes{}
	return &this
}

// GetHead returns the Head field value
func (o *CreateAgglomerationDataAttributes) GetHead() uuid.UUID {
	if o == nil {
		var ret uuid.UUID
		return ret
	}

	return o.Head
}

// GetHeadOk returns a tuple with the Head field value
// and a boolean to check if the value has been set.
func (o *CreateAgglomerationDataAttributes) GetHeadOk() (*uuid.UUID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Head, true
}

// SetHead sets field value
func (o *CreateAgglomerationDataAttributes) SetHead(v uuid.UUID) {
	o.Head = v
}

// GetName returns the Name field value
func (o *CreateAgglomerationDataAttributes) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateAgglomerationDataAttributes) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateAgglomerationDataAttributes) SetName(v string) {
	o.Name = v
}

// GetIcon returns the Icon field value if set, zero value otherwise.
func (o *CreateAgglomerationDataAttributes) GetIcon() string {
	if o == nil || IsNil(o.Icon) {
		var ret string
		return ret
	}
	return *o.Icon
}

// GetIconOk returns a tuple with the Icon field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAgglomerationDataAttributes) GetIconOk() (*string, bool) {
	if o == nil || IsNil(o.Icon) {
		return nil, false
	}
	return o.Icon, true
}

// HasIcon returns a boolean if a field has been set.
func (o *CreateAgglomerationDataAttributes) HasIcon() bool {
	if o != nil && !IsNil(o.Icon) {
		return true
	}

	return false
}

// SetIcon gets a reference to the given string and assigns it to the Icon field.
func (o *CreateAgglomerationDataAttributes) SetIcon(v string) {
	o.Icon = &v
}

func (o CreateAgglomerationDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAgglomerationDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["head"] = o.Head
	toSerialize["name"] = o.Name
	if !IsNil(o.Icon) {
		toSerialize["icon"] = o.Icon
	}
	return toSerialize, nil
}

func (o *CreateAgglomerationDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"head",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateAgglomerationDataAttributes := _CreateAgglomerationDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateAgglomerationDataAttributes)

	if err != nil {
		return err
	}

	*o = CreateAgglomerationDataAttributes(varCreateAgglomerationDataAttributes)

	return err
}

type NullableCreateAgglomerationDataAttributes struct {
	value *CreateAgglomerationDataAttributes
	isSet bool
}

func (v NullableCreateAgglomerationDataAttributes) Get() *CreateAgglomerationDataAttributes {
	return v.value
}

func (v *NullableCreateAgglomerationDataAttributes) Set(val *CreateAgglomerationDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAgglomerationDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAgglomerationDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAgglomerationDataAttributes(val *CreateAgglomerationDataAttributes) *NullableCreateAgglomerationDataAttributes {
	return &NullableCreateAgglomerationDataAttributes{value: val, isSet: true}
}

func (v NullableCreateAgglomerationDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAgglomerationDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


