/*
agglomerations-svc API

API documentation for agglomerations-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"github.com/google/uuid"
	"time"
	"bytes"
	"fmt"
)

// checks if the MemberDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MemberDataAttributes{}

// MemberDataAttributes struct for MemberDataAttributes
type MemberDataAttributes struct {
	// The ID of the account associated with the member
	AccountId uuid.UUID `json:"account_id"`
	// The ID of the agglomeration the member belongs to
	AgglomerationId uuid.UUID `json:"agglomeration_id"`
	// The position or role of the member within the agglomeration
	Position *string `json:"position,omitempty"`
	// A label or title associated with the member
	Label *string `json:"label,omitempty"`
	// The username of the member
	Username string `json:"username"`
	// Indicates if the member is an official representative of the agglomeration
	Official bool `json:"official"`
	// The date and time when the member was created
	CreatedAt time.Time `json:"created_at"`
	// The date and time when the member was last updated
	UpdatedAt time.Time `json:"updated_at"`
}

type _MemberDataAttributes MemberDataAttributes

// NewMemberDataAttributes instantiates a new MemberDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMemberDataAttributes(accountId uuid.UUID, agglomerationId uuid.UUID, username string, official bool, createdAt time.Time, updatedAt time.Time) *MemberDataAttributes {
	this := MemberDataAttributes{}
	this.AccountId = accountId
	this.AgglomerationId = agglomerationId
	this.Username = username
	this.Official = official
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewMemberDataAttributesWithDefaults instantiates a new MemberDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMemberDataAttributesWithDefaults() *MemberDataAttributes {
	this := MemberDataAttributes{}
	return &this
}

// GetAccountId returns the AccountId field value
func (o *MemberDataAttributes) GetAccountId() uuid.UUID {
	if o == nil {
		var ret uuid.UUID
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *MemberDataAttributes) GetAccountIdOk() (*uuid.UUID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *MemberDataAttributes) SetAccountId(v uuid.UUID) {
	o.AccountId = v
}

// GetAgglomerationId returns the AgglomerationId field value
func (o *MemberDataAttributes) GetAgglomerationId() uuid.UUID {
	if o == nil {
		var ret uuid.UUID
		return ret
	}

	return o.AgglomerationId
}

// GetAgglomerationIdOk returns a tuple with the AgglomerationId field value
// and a boolean to check if the value has been set.
func (o *MemberDataAttributes) GetAgglomerationIdOk() (*uuid.UUID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgglomerationId, true
}

// SetAgglomerationId sets field value
func (o *MemberDataAttributes) SetAgglomerationId(v uuid.UUID) {
	o.AgglomerationId = v
}

// GetPosition returns the Position field value if set, zero value otherwise.
func (o *MemberDataAttributes) GetPosition() string {
	if o == nil || IsNil(o.Position) {
		var ret string
		return ret
	}
	return *o.Position
}

// GetPositionOk returns a tuple with the Position field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MemberDataAttributes) GetPositionOk() (*string, bool) {
	if o == nil || IsNil(o.Position) {
		return nil, false
	}
	return o.Position, true
}

// HasPosition returns a boolean if a field has been set.
func (o *MemberDataAttributes) HasPosition() bool {
	if o != nil && !IsNil(o.Position) {
		return true
	}

	return false
}

// SetPosition gets a reference to the given string and assigns it to the Position field.
func (o *MemberDataAttributes) SetPosition(v string) {
	o.Position = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *MemberDataAttributes) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MemberDataAttributes) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *MemberDataAttributes) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *MemberDataAttributes) SetLabel(v string) {
	o.Label = &v
}

// GetUsername returns the Username field value
func (o *MemberDataAttributes) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *MemberDataAttributes) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *MemberDataAttributes) SetUsername(v string) {
	o.Username = v
}

// GetOfficial returns the Official field value
func (o *MemberDataAttributes) GetOfficial() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Official
}

// GetOfficialOk returns a tuple with the Official field value
// and a boolean to check if the value has been set.
func (o *MemberDataAttributes) GetOfficialOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Official, true
}

// SetOfficial sets field value
func (o *MemberDataAttributes) SetOfficial(v bool) {
	o.Official = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *MemberDataAttributes) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *MemberDataAttributes) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *MemberDataAttributes) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *MemberDataAttributes) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *MemberDataAttributes) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *MemberDataAttributes) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o MemberDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MemberDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["account_id"] = o.AccountId
	toSerialize["agglomeration_id"] = o.AgglomerationId
	if !IsNil(o.Position) {
		toSerialize["position"] = o.Position
	}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	toSerialize["username"] = o.Username
	toSerialize["official"] = o.Official
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *MemberDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"account_id",
		"agglomeration_id",
		"username",
		"official",
		"created_at",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMemberDataAttributes := _MemberDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMemberDataAttributes)

	if err != nil {
		return err
	}

	*o = MemberDataAttributes(varMemberDataAttributes)

	return err
}

type NullableMemberDataAttributes struct {
	value *MemberDataAttributes
	isSet bool
}

func (v NullableMemberDataAttributes) Get() *MemberDataAttributes {
	return v.value
}

func (v *NullableMemberDataAttributes) Set(val *MemberDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableMemberDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableMemberDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMemberDataAttributes(val *MemberDataAttributes) *NullableMemberDataAttributes {
	return &NullableMemberDataAttributes{value: val, isSet: true}
}

func (v NullableMemberDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMemberDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


