/*
agglomerations-svc API

API documentation for agglomerations-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"github.com/google/uuid"
	"bytes"
	"fmt"
)

// checks if the RoleDataRelationshipsPermissionsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RoleDataRelationshipsPermissionsInner{}

// RoleDataRelationshipsPermissionsInner struct for RoleDataRelationshipsPermissionsInner
type RoleDataRelationshipsPermissionsInner struct {
	// Unique identifier for the permission
	Id uuid.UUID `json:"id"`
	// A short code representing the permission
	Code string `json:"code"`
	// A detailed description of what the permission allows
	Description string `json:"description"`
	// Indicates if the role has this permission
	Enabled bool `json:"enabled"`
}

type _RoleDataRelationshipsPermissionsInner RoleDataRelationshipsPermissionsInner

// NewRoleDataRelationshipsPermissionsInner instantiates a new RoleDataRelationshipsPermissionsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoleDataRelationshipsPermissionsInner(id uuid.UUID, code string, description string, enabled bool) *RoleDataRelationshipsPermissionsInner {
	this := RoleDataRelationshipsPermissionsInner{}
	this.Id = id
	this.Code = code
	this.Description = description
	this.Enabled = enabled
	return &this
}

// NewRoleDataRelationshipsPermissionsInnerWithDefaults instantiates a new RoleDataRelationshipsPermissionsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRoleDataRelationshipsPermissionsInnerWithDefaults() *RoleDataRelationshipsPermissionsInner {
	this := RoleDataRelationshipsPermissionsInner{}
	return &this
}

// GetId returns the Id field value
func (o *RoleDataRelationshipsPermissionsInner) GetId() uuid.UUID {
	if o == nil {
		var ret uuid.UUID
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *RoleDataRelationshipsPermissionsInner) GetIdOk() (*uuid.UUID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *RoleDataRelationshipsPermissionsInner) SetId(v uuid.UUID) {
	o.Id = v
}

// GetCode returns the Code field value
func (o *RoleDataRelationshipsPermissionsInner) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *RoleDataRelationshipsPermissionsInner) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *RoleDataRelationshipsPermissionsInner) SetCode(v string) {
	o.Code = v
}

// GetDescription returns the Description field value
func (o *RoleDataRelationshipsPermissionsInner) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *RoleDataRelationshipsPermissionsInner) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *RoleDataRelationshipsPermissionsInner) SetDescription(v string) {
	o.Description = v
}

// GetEnabled returns the Enabled field value
func (o *RoleDataRelationshipsPermissionsInner) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *RoleDataRelationshipsPermissionsInner) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *RoleDataRelationshipsPermissionsInner) SetEnabled(v bool) {
	o.Enabled = v
}

func (o RoleDataRelationshipsPermissionsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RoleDataRelationshipsPermissionsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["code"] = o.Code
	toSerialize["description"] = o.Description
	toSerialize["enabled"] = o.Enabled
	return toSerialize, nil
}

func (o *RoleDataRelationshipsPermissionsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"code",
		"description",
		"enabled",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRoleDataRelationshipsPermissionsInner := _RoleDataRelationshipsPermissionsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRoleDataRelationshipsPermissionsInner)

	if err != nil {
		return err
	}

	*o = RoleDataRelationshipsPermissionsInner(varRoleDataRelationshipsPermissionsInner)

	return err
}

type NullableRoleDataRelationshipsPermissionsInner struct {
	value *RoleDataRelationshipsPermissionsInner
	isSet bool
}

func (v NullableRoleDataRelationshipsPermissionsInner) Get() *RoleDataRelationshipsPermissionsInner {
	return v.value
}

func (v *NullableRoleDataRelationshipsPermissionsInner) Set(val *RoleDataRelationshipsPermissionsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableRoleDataRelationshipsPermissionsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableRoleDataRelationshipsPermissionsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoleDataRelationshipsPermissionsInner(val *RoleDataRelationshipsPermissionsInner) *NullableRoleDataRelationshipsPermissionsInner {
	return &NullableRoleDataRelationshipsPermissionsInner{value: val, isSet: true}
}

func (v NullableRoleDataRelationshipsPermissionsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoleDataRelationshipsPermissionsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


