/*
organizations-svc API

API documentation for organizations-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateInviteData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateInviteData{}

// CreateInviteData struct for CreateInviteData
type CreateInviteData struct {
	Type string `json:"type"`
	Attributes CreateInviteDataAttributes `json:"attributes"`
}

type _CreateInviteData CreateInviteData

// NewCreateInviteData instantiates a new CreateInviteData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateInviteData(type_ string, attributes CreateInviteDataAttributes) *CreateInviteData {
	this := CreateInviteData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewCreateInviteDataWithDefaults instantiates a new CreateInviteData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateInviteDataWithDefaults() *CreateInviteData {
	this := CreateInviteData{}
	return &this
}

// GetType returns the Type field value
func (o *CreateInviteData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CreateInviteData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CreateInviteData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *CreateInviteData) GetAttributes() CreateInviteDataAttributes {
	if o == nil {
		var ret CreateInviteDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *CreateInviteData) GetAttributesOk() (*CreateInviteDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *CreateInviteData) SetAttributes(v CreateInviteDataAttributes) {
	o.Attributes = v
}

func (o CreateInviteData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateInviteData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *CreateInviteData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateInviteData := _CreateInviteData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateInviteData)

	if err != nil {
		return err
	}

	*o = CreateInviteData(varCreateInviteData)

	return err
}

type NullableCreateInviteData struct {
	value *CreateInviteData
	isSet bool
}

func (v NullableCreateInviteData) Get() *CreateInviteData {
	return v.value
}

func (v *NullableCreateInviteData) Set(val *CreateInviteData) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateInviteData) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateInviteData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateInviteData(val *CreateInviteData) *NullableCreateInviteData {
	return &NullableCreateInviteData{value: val, isSet: true}
}

func (v NullableCreateInviteData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateInviteData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


