/*
organizations-svc API

API documentation for organizations-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// checks if the UpdateRolesRanksDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateRolesRanksDataAttributes{}

// UpdateRolesRanksDataAttributes struct for UpdateRolesRanksDataAttributes
type UpdateRolesRanksDataAttributes struct {
	// An ordered list of role IDs representing the new roles hierarchy
	Roles []UpdateRolesRanksDataAttributesRolesInner `json:"roles,omitempty"`
}

// NewUpdateRolesRanksDataAttributes instantiates a new UpdateRolesRanksDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateRolesRanksDataAttributes() *UpdateRolesRanksDataAttributes {
	this := UpdateRolesRanksDataAttributes{}
	return &this
}

// NewUpdateRolesRanksDataAttributesWithDefaults instantiates a new UpdateRolesRanksDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateRolesRanksDataAttributesWithDefaults() *UpdateRolesRanksDataAttributes {
	this := UpdateRolesRanksDataAttributes{}
	return &this
}

// GetRoles returns the Roles field value if set, zero value otherwise.
func (o *UpdateRolesRanksDataAttributes) GetRoles() []UpdateRolesRanksDataAttributesRolesInner {
	if o == nil || IsNil(o.Roles) {
		var ret []UpdateRolesRanksDataAttributesRolesInner
		return ret
	}
	return o.Roles
}

// GetRolesOk returns a tuple with the Roles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateRolesRanksDataAttributes) GetRolesOk() ([]UpdateRolesRanksDataAttributesRolesInner, bool) {
	if o == nil || IsNil(o.Roles) {
		return nil, false
	}
	return o.Roles, true
}

// HasRoles returns a boolean if a field has been set.
func (o *UpdateRolesRanksDataAttributes) HasRoles() bool {
	if o != nil && !IsNil(o.Roles) {
		return true
	}

	return false
}

// SetRoles gets a reference to the given []UpdateRolesRanksDataAttributesRolesInner and assigns it to the Roles field.
func (o *UpdateRolesRanksDataAttributes) SetRoles(v []UpdateRolesRanksDataAttributesRolesInner) {
	o.Roles = v
}

func (o UpdateRolesRanksDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateRolesRanksDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Roles) {
		toSerialize["roles"] = o.Roles
	}
	return toSerialize, nil
}

type NullableUpdateRolesRanksDataAttributes struct {
	value *UpdateRolesRanksDataAttributes
	isSet bool
}

func (v NullableUpdateRolesRanksDataAttributes) Get() *UpdateRolesRanksDataAttributes {
	return v.value
}

func (v *NullableUpdateRolesRanksDataAttributes) Set(val *UpdateRolesRanksDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateRolesRanksDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateRolesRanksDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateRolesRanksDataAttributes(val *UpdateRolesRanksDataAttributes) *NullableUpdateRolesRanksDataAttributes {
	return &NullableUpdateRolesRanksDataAttributes{value: val, isSet: true}
}

func (v NullableUpdateRolesRanksDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateRolesRanksDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


