/*
agglomerations-svc API

API documentation for agglomerations-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateMember type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateMember{}

// UpdateMember struct for UpdateMember
type UpdateMember struct {
	Data UpdateMemberData `json:"data"`
}

type _UpdateMember UpdateMember

// NewUpdateMember instantiates a new UpdateMember object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateMember(data UpdateMemberData) *UpdateMember {
	this := UpdateMember{}
	this.Data = data
	return &this
}

// NewUpdateMemberWithDefaults instantiates a new UpdateMember object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateMemberWithDefaults() *UpdateMember {
	this := UpdateMember{}
	return &this
}

// GetData returns the Data field value
func (o *UpdateMember) GetData() UpdateMemberData {
	if o == nil {
		var ret UpdateMemberData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UpdateMember) GetDataOk() (*UpdateMemberData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *UpdateMember) SetData(v UpdateMemberData) {
	o.Data = v
}

func (o UpdateMember) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateMember) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *UpdateMember) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateMember := _UpdateMember{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateMember)

	if err != nil {
		return err
	}

	*o = UpdateMember(varUpdateMember)

	return err
}

type NullableUpdateMember struct {
	value *UpdateMember
	isSet bool
}

func (v NullableUpdateMember) Get() *UpdateMember {
	return v.value
}

func (v *NullableUpdateMember) Set(val *UpdateMember) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateMember) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateMember) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateMember(val *UpdateMember) *NullableUpdateMember {
	return &NullableUpdateMember{value: val, isSet: true}
}

func (v NullableUpdateMember) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateMember) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


