/*
organizations-svc API

API documentation for organizations-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// checks if the UpdateOrganizationLinksDataRelationships type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateOrganizationLinksDataRelationships{}

// UpdateOrganizationLinksDataRelationships struct for UpdateOrganizationLinksDataRelationships
type UpdateOrganizationLinksDataRelationships struct {
	Organization *UpdateOrganizationLinksDataRelationshipsOrganization `json:"organization,omitempty"`
}

// NewUpdateOrganizationLinksDataRelationships instantiates a new UpdateOrganizationLinksDataRelationships object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateOrganizationLinksDataRelationships() *UpdateOrganizationLinksDataRelationships {
	this := UpdateOrganizationLinksDataRelationships{}
	return &this
}

// NewUpdateOrganizationLinksDataRelationshipsWithDefaults instantiates a new UpdateOrganizationLinksDataRelationships object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateOrganizationLinksDataRelationshipsWithDefaults() *UpdateOrganizationLinksDataRelationships {
	this := UpdateOrganizationLinksDataRelationships{}
	return &this
}

// GetOrganization returns the Organization field value if set, zero value otherwise.
func (o *UpdateOrganizationLinksDataRelationships) GetOrganization() UpdateOrganizationLinksDataRelationshipsOrganization {
	if o == nil || IsNil(o.Organization) {
		var ret UpdateOrganizationLinksDataRelationshipsOrganization
		return ret
	}
	return *o.Organization
}

// GetOrganizationOk returns a tuple with the Organization field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOrganizationLinksDataRelationships) GetOrganizationOk() (*UpdateOrganizationLinksDataRelationshipsOrganization, bool) {
	if o == nil || IsNil(o.Organization) {
		return nil, false
	}
	return o.Organization, true
}

// HasOrganization returns a boolean if a field has been set.
func (o *UpdateOrganizationLinksDataRelationships) HasOrganization() bool {
	if o != nil && !IsNil(o.Organization) {
		return true
	}

	return false
}

// SetOrganization gets a reference to the given UpdateOrganizationLinksDataRelationshipsOrganization and assigns it to the Organization field.
func (o *UpdateOrganizationLinksDataRelationships) SetOrganization(v UpdateOrganizationLinksDataRelationshipsOrganization) {
	o.Organization = &v
}

func (o UpdateOrganizationLinksDataRelationships) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateOrganizationLinksDataRelationships) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Organization) {
		toSerialize["organization"] = o.Organization
	}
	return toSerialize, nil
}

type NullableUpdateOrganizationLinksDataRelationships struct {
	value *UpdateOrganizationLinksDataRelationships
	isSet bool
}

func (v NullableUpdateOrganizationLinksDataRelationships) Get() *UpdateOrganizationLinksDataRelationships {
	return v.value
}

func (v *NullableUpdateOrganizationLinksDataRelationships) Set(val *UpdateOrganizationLinksDataRelationships) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateOrganizationLinksDataRelationships) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateOrganizationLinksDataRelationships) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateOrganizationLinksDataRelationships(val *UpdateOrganizationLinksDataRelationships) *NullableUpdateOrganizationLinksDataRelationships {
	return &NullableUpdateOrganizationLinksDataRelationships{value: val, isSet: true}
}

func (v NullableUpdateOrganizationLinksDataRelationships) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateOrganizationLinksDataRelationships) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


