/*
organizations-svc API

API documentation for organizations-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"github.com/google/uuid"
	"bytes"
	"fmt"
)

// checks if the RolePermissionsDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RolePermissionsDataInner{}

// RolePermissionsDataInner struct for RolePermissionsDataInner
type RolePermissionsDataInner struct {
	// Unique identifier for the permission
	Id uuid.UUID `json:"id"`
	// A short code representing the permission
	Code string `json:"code"`
	// A detailed description of what the permission allows
	Description string `json:"description"`
}

type _RolePermissionsDataInner RolePermissionsDataInner

// NewRolePermissionsDataInner instantiates a new RolePermissionsDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRolePermissionsDataInner(id uuid.UUID, code string, description string) *RolePermissionsDataInner {
	this := RolePermissionsDataInner{}
	this.Id = id
	this.Code = code
	this.Description = description
	return &this
}

// NewRolePermissionsDataInnerWithDefaults instantiates a new RolePermissionsDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRolePermissionsDataInnerWithDefaults() *RolePermissionsDataInner {
	this := RolePermissionsDataInner{}
	return &this
}

// GetId returns the Id field value
func (o *RolePermissionsDataInner) GetId() uuid.UUID {
	if o == nil {
		var ret uuid.UUID
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *RolePermissionsDataInner) GetIdOk() (*uuid.UUID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *RolePermissionsDataInner) SetId(v uuid.UUID) {
	o.Id = v
}

// GetCode returns the Code field value
func (o *RolePermissionsDataInner) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *RolePermissionsDataInner) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *RolePermissionsDataInner) SetCode(v string) {
	o.Code = v
}

// GetDescription returns the Description field value
func (o *RolePermissionsDataInner) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *RolePermissionsDataInner) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *RolePermissionsDataInner) SetDescription(v string) {
	o.Description = v
}

func (o RolePermissionsDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RolePermissionsDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["code"] = o.Code
	toSerialize["description"] = o.Description
	return toSerialize, nil
}

func (o *RolePermissionsDataInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"code",
		"description",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRolePermissionsDataInner := _RolePermissionsDataInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRolePermissionsDataInner)

	if err != nil {
		return err
	}

	*o = RolePermissionsDataInner(varRolePermissionsDataInner)

	return err
}

type NullableRolePermissionsDataInner struct {
	value *RolePermissionsDataInner
	isSet bool
}

func (v NullableRolePermissionsDataInner) Get() *RolePermissionsDataInner {
	return v.value
}

func (v *NullableRolePermissionsDataInner) Set(val *RolePermissionsDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableRolePermissionsDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableRolePermissionsDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRolePermissionsDataInner(val *RolePermissionsDataInner) *NullableRolePermissionsDataInner {
	return &NullableRolePermissionsDataInner{value: val, isSet: true}
}

func (v NullableRolePermissionsDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRolePermissionsDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


