/*
agglomerations-svc API

API documentation for agglomerations-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"github.com/google/uuid"
	"bytes"
	"fmt"
)

// checks if the RolePermission type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RolePermission{}

// RolePermission struct for RolePermission
type RolePermission struct {
	// Unique identifier for the permission
	Id uuid.UUID `json:"id"`
	// A short code representing the permission
	Code string `json:"code"`
	// A detailed description of what the permission allows
	Description string `json:"description"`
}

type _RolePermission RolePermission

// NewRolePermission instantiates a new RolePermission object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRolePermission(id uuid.UUID, code string, description string) *RolePermission {
	this := RolePermission{}
	this.Id = id
	this.Code = code
	this.Description = description
	return &this
}

// NewRolePermissionWithDefaults instantiates a new RolePermission object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRolePermissionWithDefaults() *RolePermission {
	this := RolePermission{}
	return &this
}

// GetId returns the Id field value
func (o *RolePermission) GetId() uuid.UUID {
	if o == nil {
		var ret uuid.UUID
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *RolePermission) GetIdOk() (*uuid.UUID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *RolePermission) SetId(v uuid.UUID) {
	o.Id = v
}

// GetCode returns the Code field value
func (o *RolePermission) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *RolePermission) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *RolePermission) SetCode(v string) {
	o.Code = v
}

// GetDescription returns the Description field value
func (o *RolePermission) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *RolePermission) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *RolePermission) SetDescription(v string) {
	o.Description = v
}

func (o RolePermission) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RolePermission) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["code"] = o.Code
	toSerialize["description"] = o.Description
	return toSerialize, nil
}

func (o *RolePermission) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"code",
		"description",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRolePermission := _RolePermission{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRolePermission)

	if err != nil {
		return err
	}

	*o = RolePermission(varRolePermission)

	return err
}

type NullableRolePermission struct {
	value *RolePermission
	isSet bool
}

func (v NullableRolePermission) Get() *RolePermission {
	return v.value
}

func (v *NullableRolePermission) Set(val *RolePermission) {
	v.value = val
	v.isSet = true
}

func (v NullableRolePermission) IsSet() bool {
	return v.isSet
}

func (v *NullableRolePermission) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRolePermission(val *RolePermission) *NullableRolePermission {
	return &NullableRolePermission{value: val, isSet: true}
}

func (v NullableRolePermission) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRolePermission) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


