/*
agglomerations-svc API

API documentation for agglomerations-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"github.com/google/uuid"
	"bytes"
	"fmt"
)

// checks if the AgglomerationData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgglomerationData{}

// AgglomerationData struct for AgglomerationData
type AgglomerationData struct {
	// agglomeration ID
	Id uuid.UUID `json:"id"`
	Type string `json:"type"`
	Attributes AgglomerationDataAttributes `json:"attributes"`
}

type _AgglomerationData AgglomerationData

// NewAgglomerationData instantiates a new AgglomerationData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgglomerationData(id uuid.UUID, type_ string, attributes AgglomerationDataAttributes) *AgglomerationData {
	this := AgglomerationData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewAgglomerationDataWithDefaults instantiates a new AgglomerationData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgglomerationDataWithDefaults() *AgglomerationData {
	this := AgglomerationData{}
	return &this
}

// GetId returns the Id field value
func (o *AgglomerationData) GetId() uuid.UUID {
	if o == nil {
		var ret uuid.UUID
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AgglomerationData) GetIdOk() (*uuid.UUID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AgglomerationData) SetId(v uuid.UUID) {
	o.Id = v
}

// GetType returns the Type field value
func (o *AgglomerationData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AgglomerationData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AgglomerationData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *AgglomerationData) GetAttributes() AgglomerationDataAttributes {
	if o == nil {
		var ret AgglomerationDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *AgglomerationData) GetAttributesOk() (*AgglomerationDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *AgglomerationData) SetAttributes(v AgglomerationDataAttributes) {
	o.Attributes = v
}

func (o AgglomerationData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgglomerationData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *AgglomerationData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAgglomerationData := _AgglomerationData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAgglomerationData)

	if err != nil {
		return err
	}

	*o = AgglomerationData(varAgglomerationData)

	return err
}

type NullableAgglomerationData struct {
	value *AgglomerationData
	isSet bool
}

func (v NullableAgglomerationData) Get() *AgglomerationData {
	return v.value
}

func (v *NullableAgglomerationData) Set(val *AgglomerationData) {
	v.value = val
	v.isSet = true
}

func (v NullableAgglomerationData) IsSet() bool {
	return v.isSet
}

func (v *NullableAgglomerationData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgglomerationData(val *AgglomerationData) *NullableAgglomerationData {
	return &NullableAgglomerationData{value: val, isSet: true}
}

func (v NullableAgglomerationData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgglomerationData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


