/*
organizations-svc API

API documentation for organizations-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"github.com/google/uuid"
	"bytes"
	"fmt"
)

// checks if the UpdateRolesRanksDataAttributesRolesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateRolesRanksDataAttributesRolesInner{}

// UpdateRolesRanksDataAttributesRolesInner struct for UpdateRolesRanksDataAttributesRolesInner
type UpdateRolesRanksDataAttributesRolesInner struct {
	// role ID
	Id uuid.UUID `json:"id"`
	// The new rank of the role in the hierarchy
	Rank uint `json:"rank"`
}

type _UpdateRolesRanksDataAttributesRolesInner UpdateRolesRanksDataAttributesRolesInner

// NewUpdateRolesRanksDataAttributesRolesInner instantiates a new UpdateRolesRanksDataAttributesRolesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateRolesRanksDataAttributesRolesInner(id uuid.UUID, rank uint) *UpdateRolesRanksDataAttributesRolesInner {
	this := UpdateRolesRanksDataAttributesRolesInner{}
	this.Id = id
	this.Rank = rank
	return &this
}

// NewUpdateRolesRanksDataAttributesRolesInnerWithDefaults instantiates a new UpdateRolesRanksDataAttributesRolesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateRolesRanksDataAttributesRolesInnerWithDefaults() *UpdateRolesRanksDataAttributesRolesInner {
	this := UpdateRolesRanksDataAttributesRolesInner{}
	return &this
}

// GetId returns the Id field value
func (o *UpdateRolesRanksDataAttributesRolesInner) GetId() uuid.UUID {
	if o == nil {
		var ret uuid.UUID
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UpdateRolesRanksDataAttributesRolesInner) GetIdOk() (*uuid.UUID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UpdateRolesRanksDataAttributesRolesInner) SetId(v uuid.UUID) {
	o.Id = v
}

// GetRank returns the Rank field value
func (o *UpdateRolesRanksDataAttributesRolesInner) GetRank() uint {
	if o == nil {
		var ret uint
		return ret
	}

	return o.Rank
}

// GetRankOk returns a tuple with the Rank field value
// and a boolean to check if the value has been set.
func (o *UpdateRolesRanksDataAttributesRolesInner) GetRankOk() (*uint, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Rank, true
}

// SetRank sets field value
func (o *UpdateRolesRanksDataAttributesRolesInner) SetRank(v uint) {
	o.Rank = v
}

func (o UpdateRolesRanksDataAttributesRolesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateRolesRanksDataAttributesRolesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["rank"] = o.Rank
	return toSerialize, nil
}

func (o *UpdateRolesRanksDataAttributesRolesInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"rank",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateRolesRanksDataAttributesRolesInner := _UpdateRolesRanksDataAttributesRolesInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateRolesRanksDataAttributesRolesInner)

	if err != nil {
		return err
	}

	*o = UpdateRolesRanksDataAttributesRolesInner(varUpdateRolesRanksDataAttributesRolesInner)

	return err
}

type NullableUpdateRolesRanksDataAttributesRolesInner struct {
	value *UpdateRolesRanksDataAttributesRolesInner
	isSet bool
}

func (v NullableUpdateRolesRanksDataAttributesRolesInner) Get() *UpdateRolesRanksDataAttributesRolesInner {
	return v.value
}

func (v *NullableUpdateRolesRanksDataAttributesRolesInner) Set(val *UpdateRolesRanksDataAttributesRolesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateRolesRanksDataAttributesRolesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateRolesRanksDataAttributesRolesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateRolesRanksDataAttributesRolesInner(val *UpdateRolesRanksDataAttributesRolesInner) *NullableUpdateRolesRanksDataAttributesRolesInner {
	return &NullableUpdateRolesRanksDataAttributesRolesInner{value: val, isSet: true}
}

func (v NullableUpdateRolesRanksDataAttributesRolesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateRolesRanksDataAttributesRolesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


