// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: member_roles.sql

package pgdb

import (
	"context"

	"github.com/google/uuid"
)

const createMemberRole = `-- name: CreateMemberRole :exec
INSERT INTO member_roles (
    member_id,
    role_id
) VALUES (
    $1::uuid,
    $2::uuid
)
ON CONFLICT DO NOTHING
`

type CreateMemberRoleParams struct {
	MemberID uuid.UUID
	RoleID   uuid.UUID
}

func (q *Queries) CreateMemberRole(ctx context.Context, arg CreateMemberRoleParams) error {
	_, err := q.db.ExecContext(ctx, createMemberRole, arg.MemberID, arg.RoleID)
	return err
}

const deleteMemberRole = `-- name: DeleteMemberRole :exec
DELETE FROM member_roles
WHERE member_id = $1::uuid
  AND role_id = $2::uuid
`

type DeleteMemberRoleParams struct {
	MemberID uuid.UUID
	RoleID   uuid.UUID
}

func (q *Queries) DeleteMemberRole(ctx context.Context, arg DeleteMemberRoleParams) error {
	_, err := q.db.ExecContext(ctx, deleteMemberRole, arg.MemberID, arg.RoleID)
	return err
}
