// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: permisions.sql

package pgdb

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countPermissions = `-- name: CountPermissions :one
SELECT COUNT(*)::bigint
FROM permissions
WHERE ($1::text IS NULL OR code ILIKE ($1::text || '%')) AND
      ($2::text IS NULL OR code ILIKE ($2::text || '%'))
`

type CountPermissionsParams struct {
	Description sql.NullString
	Code        sql.NullString
}

func (q *Queries) CountPermissions(ctx context.Context, arg CountPermissionsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPermissions, arg.Description, arg.Code)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const filterPermissions = `-- name: FilterPermissions :many
SELECT id, code, description
FROM permissions
WHERE
    ($1::text IS NULL OR description ILIKE ($1::text || '%'))
    AND ($2::text IS NULL OR code ILIKE ($2::text || '%'))
    AND
    (
        $3::varchar IS NULL
        OR (code, id) > ($3::varchar, $4::uuid)
    )
ORDER BY code ASC, id ASC
LIMIT $5::int
`

type FilterPermissionsParams struct {
	Description sql.NullString
	Code        sql.NullString
	AfterCode   sql.NullString
	AfterID     uuid.NullUUID
	Limit       int32
}

func (q *Queries) FilterPermissions(ctx context.Context, arg FilterPermissionsParams) ([]Permission, error) {
	rows, err := q.db.QueryContext(ctx, filterPermissions,
		arg.Description,
		arg.Code,
		arg.AfterCode,
		arg.AfterID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(&i.ID, &i.Code, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPermissionByCode = `-- name: GetPermissionByCode :one
SELECT id, code, description
FROM permissions
WHERE code = $1::varchar
`

func (q *Queries) GetPermissionByCode(ctx context.Context, code string) (Permission, error) {
	row := q.db.QueryRowContext(ctx, getPermissionByCode, code)
	var i Permission
	err := row.Scan(&i.ID, &i.Code, &i.Description)
	return i, err
}

const getPermissionByID = `-- name: GetPermissionByID :one
SELECT id, code, description
FROM permissions
WHERE id = $1::uuid
`

func (q *Queries) GetPermissionByID(ctx context.Context, id uuid.UUID) (Permission, error) {
	row := q.db.QueryRowContext(ctx, getPermissionByID, id)
	var i Permission
	err := row.Scan(&i.ID, &i.Code, &i.Description)
	return i, err
}
