// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: permisions.sql

package pgdb

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countPermissionsByCode = `-- name: CountPermissionsByCode :one
SELECT COUNT(*)::bigint
FROM permissions
WHERE ($1::text IS NULL OR code ILIKE ($1::text || '%'))
`

func (q *Queries) CountPermissionsByCode(ctx context.Context, description sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPermissionsByCode, description)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const filterPermissionsByCodeCursor = `-- name: FilterPermissionsByCodeCursor :many
SELECT id, code, description
FROM permissions
WHERE
    ($1::text IS NULL OR code ILIKE ($1::text || '%'))
    AND
    (
        $2::varchar IS NULL
        OR (code, id) > ($2::varchar, $3::uuid)
    )
ORDER BY code ASC, id ASC
LIMIT $4::int
`

type FilterPermissionsByCodeCursorParams struct {
	Description sql.NullString
	AfterCode   sql.NullString
	AfterID     uuid.NullUUID
	Limit       int32
}

func (q *Queries) FilterPermissionsByCodeCursor(ctx context.Context, arg FilterPermissionsByCodeCursorParams) ([]Permission, error) {
	rows, err := q.db.QueryContext(ctx, filterPermissionsByCodeCursor,
		arg.Description,
		arg.AfterCode,
		arg.AfterID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(&i.ID, &i.Code, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPermissionByCode = `-- name: GetPermissionByCode :one
SELECT id, code, description
FROM permissions
WHERE code = $1::varchar
`

func (q *Queries) GetPermissionByCode(ctx context.Context, code string) (Permission, error) {
	row := q.db.QueryRowContext(ctx, getPermissionByCode, code)
	var i Permission
	err := row.Scan(&i.ID, &i.Code, &i.Description)
	return i, err
}

const getPermissionByID = `-- name: GetPermissionByID :one
SELECT id, code, description
FROM permissions
WHERE id = $1::uuid
`

func (q *Queries) GetPermissionByID(ctx context.Context, id uuid.UUID) (Permission, error) {
	row := q.db.QueryRowContext(ctx, getPermissionByID, id)
	var i Permission
	err := row.Scan(&i.ID, &i.Code, &i.Description)
	return i, err
}
