// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profiles.sql

package pgdb

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createProfile = `-- name: CreateProfile :one
INSERT INTO profiles (
    account_id,
    username
) VALUES (
    $1::uuid,
    $2::varchar
)
RETURNING account_id, username, updated_at, created_at
`

type CreateProfileParams struct {
	AccountID uuid.UUID
	Username  string
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.db.QueryRowContext(ctx, createProfile, arg.AccountID, arg.Username)
	var i Profile
	err := row.Scan(
		&i.AccountID,
		&i.Username,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProfile = `-- name: DeleteProfile :exec
DELETE FROM profiles
WHERE account_id = $1::uuid
`

func (q *Queries) DeleteProfile(ctx context.Context, accountID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProfile, accountID)
	return err
}

const getProfileByAccountID = `-- name: GetProfileByAccountID :one
SELECT account_id, username, updated_at, created_at
FROM profiles
WHERE account_id = $1::uuid
`

func (q *Queries) GetProfileByAccountID(ctx context.Context, accountID uuid.UUID) (Profile, error) {
	row := q.db.QueryRowContext(ctx, getProfileByAccountID, accountID)
	var i Profile
	err := row.Scan(
		&i.AccountID,
		&i.Username,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getProfileByUsername = `-- name: GetProfileByUsername :one
SELECT account_id, username, updated_at, created_at
FROM profiles
WHERE username = $1::varchar
`

func (q *Queries) GetProfileByUsername(ctx context.Context, username string) (Profile, error) {
	row := q.db.QueryRowContext(ctx, getProfileByUsername, username)
	var i Profile
	err := row.Scan(
		&i.AccountID,
		&i.Username,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listProfiles = `-- name: ListProfiles :many
SELECT account_id, username, updated_at, created_at
FROM profiles
ORDER BY created_at DESC
LIMIT $2::int
OFFSET $1::int
`

type ListProfilesParams struct {
	Offset int32
	Limit  int32
}

func (q *Queries) ListProfiles(ctx context.Context, arg ListProfilesParams) ([]Profile, error) {
	rows, err := q.db.QueryContext(ctx, listProfiles, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Profile
	for rows.Next() {
		var i Profile
		if err := rows.Scan(
			&i.AccountID,
			&i.Username,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE profiles
SET
    username = COALESCE($1::varchar, username),
    updated_at = now()
WHERE account_id = $2::uuid
RETURNING account_id, username, updated_at, created_at
`

type UpdateProfileParams struct {
	Username  sql.NullString
	AccountID uuid.UUID
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error) {
	row := q.db.QueryRowContext(ctx, updateProfile, arg.Username, arg.AccountID)
	var i Profile
	err := row.Scan(
		&i.AccountID,
		&i.Username,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
