// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: role_permissions.sql

package pgdb

import (
	"context"

	"github.com/google/uuid"
)

const createRolePermission = `-- name: CreateRolePermission :exec
INSERT INTO role_permissions (
    role_id,
    permission_id
) VALUES (
    $1, $2
)
`

type CreateRolePermissionParams struct {
	RoleID       uuid.UUID
	PermissionID uuid.UUID
}

func (q *Queries) CreateRolePermission(ctx context.Context, arg CreateRolePermissionParams) error {
	_, err := q.db.ExecContext(ctx, createRolePermission, arg.RoleID, arg.PermissionID)
	return err
}

const deleteRolePermission = `-- name: DeleteRolePermission :exec
DELETE FROM role_permissions
WHERE role_id = $1
AND permission_id = $2
`

type DeleteRolePermissionParams struct {
	RoleID       uuid.UUID
	PermissionID uuid.UUID
}

func (q *Queries) DeleteRolePermission(ctx context.Context, arg DeleteRolePermissionParams) error {
	_, err := q.db.ExecContext(ctx, deleteRolePermission, arg.RoleID, arg.PermissionID)
	return err
}

const userHasPermission = `-- name: UserHasPermission :one
SELECT EXISTS (
    SELECT 1
    FROM members m
             JOIN member_roles mr ON mr.member_id = m.id
             JOIN role_permissions rp ON rp.role_id = mr.role_id
             JOIN permissions p ON p.id = rp.permission_id
    WHERE m.account_id = $1
      AND m.agglomeration_id = $2
      AND p.code = $3
)
`

type UserHasPermissionParams struct {
	AccountID       uuid.UUID
	AgglomerationID uuid.UUID
	Code            string
}

func (q *Queries) UserHasPermission(ctx context.Context, arg UserHasPermissionParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, userHasPermission, arg.AccountID, arg.AgglomerationID, arg.Code)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
