// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: roles.sql

package pgdb

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countRolesByAgglomeration = `-- name: CountRolesByAgglomeration :one
SELECT COUNT(*)::bigint
FROM roles
WHERE agglomeration_id = $1::uuid
`

func (q *Queries) CountRolesByAgglomeration(ctx context.Context, agglomerationID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRolesByAgglomeration, agglomerationID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (
    id,
    agglomeration_id,
    head,
    editable,
    rank,
    name
) VALUES (
    $1::uuid,
    $2::uuid,
    COALESCE($3::boolean, false),
    COALESCE($4::boolean, true),
    COALESCE($5::int, 0),
    $6::text
)
RETURNING id, agglomeration_id, head, editable, rank, name, created_at, updated_at
`

type CreateRoleParams struct {
	ID              uuid.UUID
	AgglomerationID uuid.UUID
	Head            sql.NullBool
	Editable        sql.NullBool
	Rank            sql.NullInt32
	Name            string
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRowContext(ctx, createRole,
		arg.ID,
		arg.AgglomerationID,
		arg.Head,
		arg.Editable,
		arg.Rank,
		arg.Name,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.AgglomerationID,
		&i.Head,
		&i.Editable,
		&i.Rank,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM roles
WHERE id = $1::uuid
`

func (q *Queries) DeleteRole(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteRole, id)
	return err
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, agglomeration_id, head, editable, rank, name, created_at, updated_at
FROM roles
WHERE id = $1::uuid
`

func (q *Queries) GetRoleByID(ctx context.Context, id uuid.UUID) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRoleByID, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.AgglomerationID,
		&i.Head,
		&i.Editable,
		&i.Rank,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRolesByAgglomerationCursor = `-- name: ListRolesByAgglomerationCursor :many
SELECT id, agglomeration_id, head, editable, rank, name, created_at, updated_at
FROM roles
WHERE
    agglomeration_id = $1::uuid
    AND (
        $2::int IS NULL
        OR (rank, created_at, id) > (
            $2::int,
            $3::timestamptz,
            $4::uuid
        )
    )
ORDER BY rank ASC, created_at ASC, id ASC
LIMIT $5::int
`

type ListRolesByAgglomerationCursorParams struct {
	AgglomerationID uuid.UUID
	AfterRank       sql.NullInt32
	AfterCreatedAt  sql.NullTime
	AfterID         uuid.NullUUID
	Limit           int32
}

func (q *Queries) ListRolesByAgglomerationCursor(ctx context.Context, arg ListRolesByAgglomerationCursorParams) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, listRolesByAgglomerationCursor,
		arg.AgglomerationID,
		arg.AfterRank,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.AgglomerationID,
			&i.Head,
			&i.Editable,
			&i.Rank,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRole = `-- name: UpdateRole :one
UPDATE roles
SET
    head = COALESCE($1::boolean, head),
    editable = COALESCE($2::boolean, editable),
    rank = COALESCE($3::int, rank),

    name = COALESCE($4::text, name),

    updated_at = now()
WHERE id = $5::uuid
RETURNING id, agglomeration_id, head, editable, rank, name, created_at, updated_at
`

type UpdateRoleParams struct {
	Head     sql.NullBool
	Editable sql.NullBool
	Rank     sql.NullInt32
	Name     sql.NullString
	ID       uuid.UUID
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error) {
	row := q.db.QueryRowContext(ctx, updateRole,
		arg.Head,
		arg.Editable,
		arg.Rank,
		arg.Name,
		arg.ID,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.AgglomerationID,
		&i.Head,
		&i.Editable,
		&i.Rank,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
