// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: role_permissions.sql

package pgdb

import (
	"context"

	"github.com/google/uuid"
)

const checkMemberHavePermissionByCode = `-- name: CheckMemberHavePermissionByCode :one
SELECT EXISTS (
    SELECT 1
    FROM members m
    JOIN member_roles mr ON mr.member_id = m.id
    JOIN role_permissions rp ON rp.role_id = mr.role_id
    JOIN permissions p ON p.id = rp.permission_id
    WHERE m.id = $1::uuid
        AND m.agglomeration_id = $2::uuid
        AND p.code = $3::text
)
`

type CheckMemberHavePermissionByCodeParams struct {
	MemberID        uuid.UUID
	AgglomerationID uuid.UUID
	Code            string
}

func (q *Queries) CheckMemberHavePermissionByCode(ctx context.Context, arg CheckMemberHavePermissionByCodeParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkMemberHavePermissionByCode, arg.MemberID, arg.AgglomerationID, arg.Code)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkMemberHavePermissionByID = `-- name: CheckMemberHavePermissionByID :one
SELECT EXISTS (
    SELECT 1
    FROM members m
    JOIN member_roles mr ON mr.member_id = m.id
    JOIN role_permissions rp ON rp.role_id = mr.role_id
    WHERE m.id = $1::uuid
        AND m.agglomeration_id = $2::uuid
        AND rp.permission_id = $3::uuid
)
`

type CheckMemberHavePermissionByIDParams struct {
	MemberID        uuid.UUID
	AgglomerationID uuid.UUID
	PermissionID    uuid.UUID
}

func (q *Queries) CheckMemberHavePermissionByID(ctx context.Context, arg CheckMemberHavePermissionByIDParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkMemberHavePermissionByID, arg.MemberID, arg.AgglomerationID, arg.PermissionID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createRolePermission = `-- name: CreateRolePermission :exec
INSERT INTO role_permissions (
    role_id,
    permission_id
) VALUES (
    $1, $2
)
`

type CreateRolePermissionParams struct {
	RoleID       uuid.UUID
	PermissionID uuid.UUID
}

func (q *Queries) CreateRolePermission(ctx context.Context, arg CreateRolePermissionParams) error {
	_, err := q.db.ExecContext(ctx, createRolePermission, arg.RoleID, arg.PermissionID)
	return err
}

const deleteRolePermission = `-- name: DeleteRolePermission :exec
DELETE FROM role_permissions
WHERE role_id = $1
AND permission_id = $2
`

type DeleteRolePermissionParams struct {
	RoleID       uuid.UUID
	PermissionID uuid.UUID
}

func (q *Queries) DeleteRolePermission(ctx context.Context, arg DeleteRolePermissionParams) error {
	_, err := q.db.ExecContext(ctx, deleteRolePermission, arg.RoleID, arg.PermissionID)
	return err
}
