openapi: 3.1.1
info:
  description: API documentation for organizations-svc
  title: organizations-svc API
  version: 0.1.0
servers:
- url: /
paths:
  /test:
    post:
      description: Test
      responses:
        "201":
          description: successfully
      tags:
      - Test
components:
  schemas:
    CreateOrganization:
      properties:
        data:
          $ref: "#/components/schemas/CreateOrganization_data"
      required:
      - data
    UpdateOrganization:
      properties:
        data:
          $ref: "#/components/schemas/UpdateOrganization_data"
      required:
      - data
    UpdateMember:
      properties:
        data:
          $ref: "#/components/schemas/UpdateMember_data"
      required:
      - data
    CreateInvite:
      properties:
        data:
          $ref: "#/components/schemas/CreateInvite_data"
      required:
      - data
    DeleteUploadOrgIcon:
      properties:
        data:
          $ref: "#/components/schemas/DeleteUploadOrgIcon_data"
      required:
      - data
    DeleteUploadOrgBanner:
      properties:
        data:
          $ref: "#/components/schemas/DeleteUploadOrgBanner_data"
      required:
      - data
    PaginationData:
      properties:
        self:
          description: link to the current page
          format: uri
          type: string
        first:
          description: link to the first page
          format: uri
          type: string
        last:
          description: link to the last page
          format: uri
          type: string
        prev:
          description: link to the previous page
          format: uri
          type: string
        next:
          description: link to the next page
          format: uri
          type: string
      required:
      - self
    UploadResourcesLink:
      properties:
        key:
          description: Key for the avatar in the storage service
          type: string
        upload_url:
          description: Pre-signed URL for uploading the avatar
          format: uri
          type: string
        preload_url:
          description: URL for preloading the avatar after upload
          format: uri
          type: string
      required:
      - key
      - preload_url
      - upload_url
    ProfileData:
      properties:
        id:
          description: account id
          format: uuid
          type: string
        type:
          enum:
          - profile
          type: string
        attributes:
          $ref: "#/components/schemas/ProfileAttributes"
      required:
      - attributes
      - id
      - type
    ProfileAttributes:
      properties:
        username:
          description: username for this account and profile
          type: string
        pseudonym:
          description: profile pseudonym
          type: string
        official:
          description: official mark
          type: boolean
        avatar_key:
          description: avatar key
          type: string
        version:
          description: profile version
          type: integer
        updated_at:
          description: updated at
          format: date-time
          type: string
        created_at:
          description: created at
          format: date-time
          type: string
      required:
      - created_at
      - official
      - updated_at
      - username
      - version
    Organization:
      properties:
        data:
          $ref: "#/components/schemas/OrganizationData"
      required:
      - data
    OrganizationData:
      properties:
        id:
          description: organization ID
          format: uuid
          type: string
        type:
          enum:
          - organization
          type: string
        attributes:
          $ref: "#/components/schemas/OrganizationData_attributes"
      required:
      - attributes
      - id
      - type
    OrganizationsCollection:
      properties:
        data:
          items:
            $ref: "#/components/schemas/OrganizationData"
          type: array
        included:
          items:
            $ref: "#/components/schemas/Member/properties/data"
          type: array
        links:
          $ref: "#/components/schemas/PaginationData"
      required:
      - data
      - links
    UploadOrgMediaLinks:
      properties:
        data:
          $ref: "#/components/schemas/UploadOrgMediaLinks_data"
        included:
          items:
            $ref: "#/components/schemas/OrganizationData"
          type: array
      required:
      - data
      - included
    Member:
      properties:
        data:
          $ref: "#/components/schemas/Member_data"
        included:
          items:
            $ref: "#/components/schemas/MemberIncluded_inner"
          type: array
      required:
      - data
    MemberCollection:
      properties:
        data:
          items:
            $ref: "#/components/schemas/Member/properties/data"
          type: array
        included:
          items:
            $ref: "#/components/schemas/MemberIncluded_inner"
          type: array
        links:
          $ref: "#/components/schemas/PaginationData"
      required:
      - data
      - links
    MemberIncluded:
      items:
        $ref: "#/components/schemas/MemberIncluded_inner"
      type: array
    Invite:
      properties:
        data:
          $ref: "#/components/schemas/Invite_data"
        included:
          items:
            $ref: "#/components/schemas/InviteIncluded_inner"
          type: array
      required:
      - data
    InvitesCollection:
      properties:
        data:
          items:
            $ref: "#/components/schemas/Invite/properties/data"
          type: array
        included:
          items:
            $ref: "#/components/schemas/InviteIncluded_inner"
          type: array
        links:
          $ref: "#/components/schemas/PaginationData"
      required:
      - data
      - links
    InviteIncluded:
      items:
        $ref: "#/components/schemas/InviteIncluded_inner"
      type: array
    data:
      properties:
        id:
          description: Invite ID
          format: uuid
          type: string
        type:
          enum:
          - invite
          type: string
        attributes:
          $ref: "#/components/schemas/Invite_data_attributes"
        relationships:
          $ref: "#/components/schemas/Member_data_relationships"
      required:
      - attributes
      - id
      - relationships
      - type
    CreateOrganization_data_attributes:
      properties:
        name:
          description: The name of the organization
          type: string
      required:
      - name
    CreateOrganization_data:
      properties:
        type:
          enum:
          - organization
          type: string
        attributes:
          $ref: "#/components/schemas/CreateOrganization_data_attributes"
      required:
      - attributes
      - type
    UpdateOrganization_data_attributes:
      properties:
        name:
          description: The name of the organization
          type: string
        icon_key:
          description: The media key for the organization's icon
          type: string
        banner_key:
          description: The media key for the organization's banner
          type: string
      required:
      - name
    UpdateOrganization_data:
      properties:
        id:
          description: organization ID
          format: uuid
          type: string
        type:
          enum:
          - organization
          type: string
        attributes:
          $ref: "#/components/schemas/UpdateOrganization_data_attributes"
      required:
      - attributes
      - id
      - type
    UpdateMember_data_attributes:
      properties:
        position:
          description: The position or role of the member within the organization
          type: string
        label:
          description: A label or title associated with the member
          type: string
    UpdateMember_data:
      properties:
        id:
          description: member ID
          format: uuid
          type: string
        type:
          enum:
          - organization_member
          type: string
        attributes:
          $ref: "#/components/schemas/UpdateMember_data_attributes"
      required:
      - attributes
      - id
      - type
    CreateInvite_data_attributes:
      properties:
        organization_id:
          description: The ID of the organization to which the invite belongs
          format: uuid
          type: string
        account_id:
          description: The ID of the account that was invited
          format: uuid
          type: string
      required:
      - account_id
      - organization_id
    CreateInvite_data:
      properties:
        type:
          enum:
          - invite
          type: string
        attributes:
          $ref: "#/components/schemas/CreateInvite_data_attributes"
      required:
      - attributes
      - type
    DeleteUploadOrgIcon_data_attributes:
      properties:
        icon_key:
          description: icon media key
          type: string
      required:
      - icon_key
    DeleteUploadOrgIcon_data:
      properties:
        id:
          description: organization id
          format: uuid
          type: string
        type:
          enum:
          - organization
          type: string
        attributes:
          $ref: "#/components/schemas/DeleteUploadOrgIcon_data_attributes"
      required:
      - attributes
      - id
      - type
    DeleteUploadOrgBanner_data_attributes:
      properties:
        banner_key:
          description: icon media key
          type: string
      required:
      - banner_key
    DeleteUploadOrgBanner_data:
      properties:
        id:
          description: organization id
          format: uuid
          type: string
        type:
          enum:
          - organization
          type: string
        attributes:
          $ref: "#/components/schemas/DeleteUploadOrgBanner_data_attributes"
      required:
      - attributes
      - id
      - type
    OrganizationData_attributes:
      properties:
        status:
          description: The status of the organization
          type: string
        name:
          description: The name of the organization
          type: string
        icon_key:
          description: The media key for the organization's icon
          type: string
        banner_key:
          description: The media key for the organization's banner
          type: string
        version:
          description: "The version number of the organization, used for optimistic\
            \ concurrency control"
          type: integer
        created_at:
          description: The date and time when the organization was created
          format: date-time
          type: string
        updated_at:
          description: The date and time when the organization was last updated
          format: date-time
          type: string
      required:
      - created_at
      - name
      - status
      - updated_at
      - version
    UploadOrgMediaLinks_data_attributes:
      properties:
        icon:
          $ref: "#/components/schemas/UploadResourcesLink"
        banner:
          $ref: "#/components/schemas/UploadResourcesLink"
      required:
      - banner
      - icon
    UploadOrgMediaLinks_data_relationships_organization_data:
      properties:
        id:
          description: organization id
          format: uuid
          type: string
        type:
          enum:
          - organization
          type: string
      required:
      - id
      - type
    UploadOrgMediaLinks_data_relationships_organization:
      properties:
        data:
          $ref: "#/components/schemas/UploadOrgMediaLinks_data_relationships_organization_data"
      required:
      - data
    UploadOrgMediaLinks_data_relationships:
      properties:
        organization:
          $ref: "#/components/schemas/UploadOrgMediaLinks_data_relationships_organization"
    UploadOrgMediaLinks_data:
      properties:
        id:
          description: organization id
          format: uuid
          type: string
        type:
          enum:
          - organization_upload_links
          type: string
        attributes:
          $ref: "#/components/schemas/UploadOrgMediaLinks_data_attributes"
        relationships:
          $ref: "#/components/schemas/UploadOrgMediaLinks_data_relationships"
      required:
      - attributes
      - id
      - relationships
      - type
    Member_data_attributes:
      properties:
        head:
          description: Indicates if the member is the head of the organization
          type: boolean
        position:
          description: The position or role of the member within the organization
          type: string
        label:
          description: A label or title associated with the member
          type: string
        version:
          description: "The version number of the member record, used for optimistic\
            \ locking"
          type: integer
        created_at:
          description: The date and time when the member was created
          format: date-time
          type: string
        updated_at:
          description: The date and time when the member was last updated
          format: date-time
          type: string
      required:
      - created_at
      - head
      - updated_at
      - version
    Member_data_relationships_organization_data:
      properties:
        type:
          enum:
          - organization
          type: string
        id:
          format: uuid
          type: string
      required:
      - id
      - type
    Member_data_relationships_organization:
      properties:
        data:
          $ref: "#/components/schemas/Member_data_relationships_organization_data"
      required:
      - data
    Member_data_relationships_profile_data:
      properties:
        type:
          enum:
          - profile
          type: string
        id:
          format: uuid
          type: string
      required:
      - id
      - type
    Member_data_relationships_profile:
      properties:
        data:
          $ref: "#/components/schemas/Member_data_relationships_profile_data"
      required:
      - data
    Member_data_relationships:
      properties:
        organization:
          $ref: "#/components/schemas/Member_data_relationships_organization"
        profile:
          $ref: "#/components/schemas/Member_data_relationships_profile"
      required:
      - organization
      - profile
    Member_data:
      properties:
        id:
          description: member ID
          format: uuid
          type: string
        type:
          enum:
          - member
          type: string
        attributes:
          $ref: "#/components/schemas/Member_data_attributes"
        relationships:
          $ref: "#/components/schemas/Member_data_relationships"
      required:
      - attributes
      - id
      - relationships
      - type
    MemberIncluded_inner:
      description: "Included related resources for members (e.g., organization)"
      oneOf:
      - $ref: "#/components/schemas/ProfileData"
      - $ref: "#/components/schemas/OrganizationData"
    Invite_data_attributes:
      properties:
        status:
          description: The status of the invite
          enum:
          - sent
          - accepted
          - declined
          type: string
        expires_at:
          description: The expiration date and time of the invite
          format: date-time
          type: string
        created_at:
          description: The date and time when the invite was created
          format: date-time
          type: string
      required:
      - created_at
      - expires_at
      - status
    Invite_data:
      properties:
        id:
          description: Invite ID
          format: uuid
          type: string
        type:
          enum:
          - invite
          type: string
        attributes:
          $ref: "#/components/schemas/Invite_data_attributes"
        relationships:
          $ref: "#/components/schemas/Member_data_relationships"
      required:
      - attributes
      - id
      - relationships
      - type
    InviteIncluded_inner:
      description: "Included related resources  for invites (e.g., organization, profile)"
      oneOf:
      - $ref: "#/components/schemas/ProfileData"
      - $ref: "#/components/schemas/OrganizationData"
