openapi: 3.1.1
info:
  title: organizations-svc API
  description: API documentation for organizations-svc
  version: 0.1.0
paths:
  /test:
    post:
      tags:
        - Test
      description: Test
      responses:
        '201':
          description: successfully
components:
  schemas:
    CreateOrganization:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - type
            - attributes
          properties:
            type:
              type: string
              enum:
                - organization
            attributes:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  description: The name of the organization
    UpdateOrganization:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              description: organization ID
            type:
              type: string
              enum:
                - organization
            attributes:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  description: The name of the organization
                icon_key:
                  type: string
                  description: The media key for the organization's icon
                banner_key:
                  type: string
                  description: The media key for the organization's banner
    UpdateMember:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              description: member ID
            type:
              type: string
              enum:
                - organization_member
            attributes:
              type: object
              properties:
                position:
                  type: string
                  description: The position or role of the member within the organization
                label:
                  type: string
                  description: A label or title associated with the member
    CreateInvite:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - type
            - attributes
          properties:
            type:
              type: string
              enum:
                - invite
            attributes:
              type: object
              required:
                - organization_id
                - account_id
              properties:
                organization_id:
                  type: string
                  format: uuid
                  description: The ID of the organization to which the invite belongs
                account_id:
                  type: string
                  format: uuid
                  description: The ID of the account that was invited
    DeleteUploadOrgIcon:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              description: organization id
            type:
              type: string
              enum:
                - organization
            attributes:
              type: object
              required:
                - icon_key
              properties:
                icon_key:
                  type: string
                  description: icon media key
    DeleteUploadOrgBanner:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              description: organization id
            type:
              type: string
              enum:
                - organization
            attributes:
              type: object
              required:
                - banner_key
              properties:
                banner_key:
                  type: string
                  description: icon media key
    PaginationData:
      type: object
      required:
        - self
      properties:
        self:
          type: string
          format: uri
          description: link to the current page
        first:
          type: string
          format: uri
          description: link to the first page
        last:
          type: string
          format: uri
          description: link to the last page
        prev:
          type: string
          format: uri
          description: link to the previous page
        next:
          type: string
          format: uri
          description: link to the next page
    UploadResourcesLink:
      type: object
      required:
        - key
        - upload_url
        - preload_url
      properties:
        key:
          type: string
          description: Key for the avatar in the storage service
        upload_url:
          type: string
          format: uri
          description: Pre-signed URL for uploading the avatar
        preload_url:
          type: string
          format: uri
          description: URL for preloading the avatar after upload
    ProfileData:
      type: object
      required:
        - id
        - type
        - attributes
      properties:
        id:
          type: string
          format: uuid
          description: account id
        type:
          type: string
          enum:
            - profile
        attributes:
          $ref: '#/components/schemas/ProfileAttributes'
    ProfileAttributes:
      type: object
      required:
        - username
        - official
        - version
        - updated_at
        - created_at
      properties:
        username:
          type: string
          description: username for this account and profile
        pseudonym:
          type: string
          description: profile pseudonym
        official:
          type: boolean
          description: official mark
        avatar_key:
          type: string
          description: avatar key
        version:
          type: integer
          description: profile version
        updated_at:
          type: string
          format: date-time
          description: updated at
        created_at:
          type: string
          format: date-time
          description: created at
    Organization:
      type: object
      required:
        - data
      properties:
        data:
          $ref: '#/components/schemas/OrganizationData'
    OrganizationData:
      type: object
      required:
        - id
        - type
        - attributes
      properties:
        id:
          type: string
          format: uuid
          description: organization ID
        type:
          type: string
          enum:
            - organization
        attributes:
          type: object
          required:
            - status
            - name
            - version
            - created_at
            - updated_at
          properties:
            status:
              type: string
              description: The status of the organization
            name:
              type: string
              description: The name of the organization
            icon_key:
              type: string
              description: The media key for the organization's icon
            banner_key:
              type: string
              description: The media key for the organization's banner
            version:
              type: integer
              description: 'The version number of the organization, used for optimistic concurrency control'
            created_at:
              type: string
              format: date-time
              description: The date and time when the organization was created
            updated_at:
              type: string
              format: date-time
              description: The date and time when the organization was last updated
    OrganizationsCollection:
      type: object
      required:
        - data
        - links
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/OrganizationData'
        included:
          type: array
          items:
            oneOf:
              - $ref: '#/components/schemas/Member/properties/data'
        links:
          $ref: '#/components/schemas/PaginationData'
    UploadOrgMediaLinks:
      type: object
      required:
        - data
        - included
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
            - relationships
          properties:
            id:
              type: string
              format: uuid
              description: organization id
            type:
              type: string
              enum:
                - organization_upload_links
            attributes:
              type: object
              required:
                - icon
                - banner
              properties:
                icon:
                  $ref: '#/components/schemas/UploadResourcesLink'
                banner:
                  $ref: '#/components/schemas/UploadResourcesLink'
            relationships:
              type: object
              properties:
                organization:
                  type: object
                  required:
                    - data
                  properties:
                    data:
                      type: object
                      required:
                        - id
                        - type
                      properties:
                        id:
                          type: string
                          format: uuid
                          description: organization id
                        type:
                          type: string
                          enum:
                            - organization
        included:
          type: array
          items:
            $ref: '#/components/schemas/OrganizationData'
    Member:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
            - relationships
          properties:
            id:
              type: string
              format: uuid
              description: member ID
            type:
              type: string
              enum:
                - member
            attributes:
              type: object
              required:
                - head
                - created_at
                - updated_at
                - version
              properties:
                head:
                  type: boolean
                  description: Indicates if the member is the head of the organization
                position:
                  type: string
                  description: The position or role of the member within the organization
                label:
                  type: string
                  description: A label or title associated with the member
                version:
                  type: integer
                  description: 'The version number of the member record, used for optimistic locking'
                created_at:
                  type: string
                  format: date-time
                  description: The date and time when the member was created
                updated_at:
                  type: string
                  format: date-time
                  description: The date and time when the member was last updated
            relationships:
              type: object
              required:
                - organization
                - profile
              properties:
                organization:
                  type: object
                  required:
                    - data
                  properties:
                    data:
                      type: object
                      required:
                        - type
                        - id
                      properties:
                        type:
                          type: string
                          enum:
                            - organization
                        id:
                          type: string
                          format: uuid
                profile:
                  type: object
                  required:
                    - data
                  properties:
                    data:
                      type: object
                      required:
                        - type
                        - id
                      properties:
                        type:
                          type: string
                          enum:
                            - profile
                        id:
                          type: string
                          format: uuid
        included:
          $ref: '#/components/schemas/MemberIncluded'
    MemberCollection:
      type: object
      required:
        - data
        - links
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Member/properties/data'
        included:
          $ref: '#/components/schemas/MemberIncluded'
        links:
          $ref: '#/components/schemas/PaginationData'
    MemberIncluded:
      type: array
      items:
        description: 'Included related resources for members (e.g., organization)'
        oneOf:
          - $ref: '#/components/schemas/ProfileData'
          - $ref: '#/components/schemas/OrganizationData'
    Invite:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
            - relationships
          properties:
            id:
              type: string
              format: uuid
              description: Invite ID
            type:
              type: string
              enum:
                - invite
            attributes:
              type: object
              required:
                - status
                - expires_at
                - created_at
              properties:
                status:
                  type: string
                  enum:
                    - sent
                    - accepted
                    - declined
                  description: The status of the invite
                expires_at:
                  type: string
                  format: date-time
                  description: The expiration date and time of the invite
                created_at:
                  type: string
                  format: date-time
                  description: The date and time when the invite was created
            relationships:
              type: object
              required:
                - organization
                - profile
              properties:
                organization:
                  type: object
                  required:
                    - data
                  properties:
                    data:
                      type: object
                      required:
                        - type
                        - id
                      properties:
                        type:
                          type: string
                          enum:
                            - organization
                        id:
                          type: string
                          format: uuid
                profile:
                  type: object
                  required:
                    - data
                  properties:
                    data:
                      type: object
                      required:
                        - type
                        - id
                      properties:
                        type:
                          type: string
                          enum:
                            - profile
                        id:
                          type: string
                          format: uuid
        included:
          $ref: '#/components/schemas/InviteIncluded'
    InvitesCollection:
      type: object
      required:
        - data
        - links
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Invite/properties/data'
        included:
          $ref: '#/components/schemas/InviteIncluded'
        links:
          $ref: '#/components/schemas/PaginationData'
    InviteIncluded:
      type: array
      items:
        description: 'Included related resources  for invites (e.g., organization, profile)'
        oneOf:
          - $ref: '#/components/schemas/ProfileData'
          - $ref: '#/components/schemas/OrganizationData'
