openapi: 3.1.0
info:
  title: organizations-svc API
  description: API documentation for organizations-svc
  version: 0.1.0
paths:
  /test:
    post:
      tags:
        - Test
      description: Test
      responses:
        '201':
          description: successfully
components:
  schemas:
    CreateOrganization:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - type
            - attributes
          properties:
            type:
              type: string
              enum:
                - organization
            attributes:
              type: object
              required:
                - head
                - name
              properties:
                head:
                  type: string
                  format: uuid
                  description: Account ID of the head of the organization
                name:
                  type: string
                  description: The name of the organization
                icon:
                  type: string
                  description: The icon representing the organization
    UpdateOrganization:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              description: organization ID
            type:
              type: string
              enum:
                - organization
            attributes:
              type: object
              properties:
                name:
                  type: string
                  description: The name of the organization
                icon:
                  type: string
                  description: The icon representing the organization
    UpdateMember:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              description: member ID
            type:
              type: string
              enum:
                - update_member
            attributes:
              type: object
              properties:
                position:
                  type: string
                  description: The position or role of the member within the organization
                label:
                  type: string
                  description: A label or title associated with the member
    SentInvite:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - type
            - attributes
          properties:
            type:
              type: string
              enum:
                - sent_invite
            attributes:
              type: object
              required:
                - organization_id
                - account_id
              properties:
                organization_id:
                  type: string
                  format: uuid
                  description: The ID of the organization to which the invite belongs
                account_id:
                  type: string
                  format: uuid
                  description: The ID of the account that was invited
    CreateRole:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - type
            - attributes
          properties:
            type:
              type: string
              enum:
                - create_role
            attributes:
              type: object
              required:
                - organization_id
                - rank
                - name
                - description
                - color
              properties:
                organization_id:
                  type: string
                  format: uuid
                  description: The ID of the organization this role belongs to
                rank:
                  type: integer
                  format: uint
                  description: The rank of the role within the organization
                name:
                  type: string
                  description: The name of the role
                description:
                  type: string
                  description: A brief description of the role
                color:
                  type: string
                  description: The color associated with the role in HEX format
    UpdateRole:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              description: role ID
            type:
              type: string
              enum:
                - update_role
            attributes:
              type: object
              properties:
                name:
                  type: string
                  description: The name of the role
                description:
                  type: string
                  description: A brief description of the role
                color:
                  type: string
                  description: The color associated with the role in HEX format
    UpdateRolesRanks:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              description: organization ID
            type:
              type: string
              enum:
                - update_roles_ranks
            attributes:
              type: object
              properties:
                roles:
                  type: array
                  description: An ordered list of role IDs representing the new roles hierarchy
                  items:
                    type: object
                    required:
                      - id
                      - rank
                    properties:
                      id:
                        type: string
                        format: uuid
                        description: role ID
                      rank:
                        type: integer
                        format: uint
                        description: The new rank of the role in the hierarchy
    UpdateRolePermissions:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              description: role ID
            type:
              type: string
              enum:
                - update_roles_permission
            attributes:
              type: object
              properties:
                roles:
                  type: array
                  description: An ordered list of role IDs representing the new roles hierarchy
                  items:
                    type: object
                    required:
                      - code
                      - status
                    properties:
                      code:
                        type: string
                        description: permission code
                      status:
                        type: boolean
                        description: The new status of the permission for the role
    PaginationData:
      type: object
      required:
        - self
      properties:
        self:
          type: string
          format: uri
          description: link to the current page
        first:
          type: string
          format: uri
          description: link to the first page
        last:
          type: string
          format: uri
          description: link to the last page
        prev:
          type: string
          format: uri
          description: link to the previous page
        next:
          type: string
          format: uri
          description: link to the next page
    Organization:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              description: organization ID
            type:
              type: string
              enum:
                - organization
            attributes:
              type: object
              required:
                - status
                - name
                - icon
                - created_at
                - updated_at
              properties:
                status:
                  type: string
                  description: The status of the organization
                name:
                  type: string
                  description: The name of the organization
                icon:
                  type: string
                  description: The icon representing the organization
                created_at:
                  type: string
                  format: date-time
                  description: The date and time when the organization was created
                updated_at:
                  type: string
                  format: date-time
                  description: The date and time when the organization was last updated
    OrganizationsCollection:
      type: object
      required:
        - data
        - links
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Organization/properties/data'
        links:
          $ref: '#/components/schemas/PaginationData'
    Member:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              description: member ID
            type:
              type: string
              enum:
                - member
            attributes:
              type: object
              required:
                - account_id
                - organization_id
                - username
                - official
                - created_at
                - updated_at
              properties:
                account_id:
                  type: string
                  format: uuid
                  description: The ID of the account associated with the member
                organization_id:
                  type: string
                  format: uuid
                  description: The ID of the organization the member belongs to
                position:
                  type: string
                  description: The position or role of the member within the organization
                label:
                  type: string
                  description: A label or title associated with the member
                username:
                  type: string
                  description: The username of the member
                official:
                  type: boolean
                  description: Indicates if the member is an official representative of the organization
                created_at:
                  type: string
                  format: date-time
                  description: The date and time when the member was created
                updated_at:
                  type: string
                  format: date-time
                  description: The date and time when the member was last updated
    MemberCollection:
      type: object
      required:
        - data
        - links
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Member/properties/data'
        links:
          $ref: '#/components/schemas/PaginationData'
    Invite:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              description: invite ID
            type:
              type: string
              enum:
                - invite
            attributes:
              type: object
              required:
                - organization_id
                - account_id
                - status
                - expires_at
                - created_at
              properties:
                organization_id:
                  type: string
                  format: uuid
                  description: The ID of the organization to which the invite belongs
                account_id:
                  type: string
                  format: uuid
                  description: The ID of the account that was invited
                status:
                  type: string
                  enum:
                    - sent
                    - accepted
                    - declined
                  description: The status of the invite
                expires_at:
                  type: string
                  format: date-time
                  description: The expiration date and time of the invite
                created_at:
                  type: string
                  format: date-time
                  description: The date and time when the invite was created
    InvitesCollection:
      type: object
      required:
        - data
        - links
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Invite/properties/data'
        links:
          $ref: '#/components/schemas/PaginationData'
    Role:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              description: member ID
            type:
              type: string
              enum:
                - role
            attributes:
              type: object
              required:
                - organization_id
                - head
                - rank
                - name
                - description
                - color
                - created_at
                - updated_at
              properties:
                organization_id:
                  type: string
                  format: uuid
                  description: The ID of the organization this role belongs to
                head:
                  type: boolean
                  description: Indicates if this role is the head role of the organization
                rank:
                  type: integer
                  format: uint
                  description: The rank of the role within the organization
                name:
                  type: string
                  description: The name of the role
                description:
                  type: string
                  description: A brief description of the role
                color:
                  type: string
                  description: The color associated with the role in HEX format
                created_at:
                  type: string
                  format: date-time
                  description: Timestamp when the role was created
                updated_at:
                  type: string
                  format: date-time
                  description: Timestamp when the role was last updated
            relationships:
              type: object
              properties:
                permissions:
                  type: array
                  items:
                    type: object
                    required:
                      - id
                      - code
                      - description
                      - enabled
                    properties:
                      id:
                        type: string
                        format: uuid
                        description: Unique identifier for the permission
                      code:
                        type: string
                        example: agglmeration.manage
                        description: A short code representing the permission
                      description:
                        type: string
                        example: Allows managing organization
                        description: A detailed description of what the permission allows
                      enabled:
                        type: boolean
                        description: Indicates if the role has this permission
    RolesCollection:
      type: object
      required:
        - data
        - links
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Role/properties/data'
        links:
          $ref: '#/components/schemas/PaginationData'
    RolePermissions:
      type: object
      required:
        - data
      properties:
        data:
          type: array
          items:
            type: object
            required:
              - id
              - code
              - description
            properties:
              id:
                type: string
                format: uuid
                description: Unique identifier for the permission
              code:
                type: string
                example: agglmeration.manage
                description: A short code representing the permission
              description:
                type: string
                example: Allows managing organization
                description: A detailed description of what the permission allows
