openapi: 3.1.0
info:
  title: cities-svc API
  description: API documentation for cities-svc
  version: 0.1.0
paths:
  /test:
    post:
      tags:
        - Test
      description: Test
      responses:
        '201':
          description: successfully
components:
  schemas:
    CreateAgglomeration:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - type
            - attributes
          properties:
            type:
              type: string
              enum:
                - agglomeration
            attributes:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  description: The name of the agglomeration
                icon:
                  type: string
                  description: The icon representing the agglomeration
    UpdateAgglomeration:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              description: agglomeration ID
            type:
              type: string
              enum:
                - agglomeration
            attributes:
              type: object
              properties:
                name:
                  type: string
                  description: The name of the agglomeration
                icon:
                  type: string
                  description: The icon representing the agglomeration
    Agglomeration:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              description: agglomeration ID
            type:
              type: string
              enum:
                - agglomeration
            attributes:
              type: object
              required:
                - status
                - name
                - icon
                - created_at
                - updated_at
              properties:
                status:
                  type: string
                  description: The status of the agglomeration
                name:
                  type: string
                  description: The name of the agglomeration
                icon:
                  type: string
                  description: The icon representing the agglomeration
                created_at:
                  type: string
                  format: date-time
                  description: The date and time when the agglomeration was created
                updated_at:
                  type: string
                  format: date-time
                  description: The date and time when the agglomeration was last updated
    AgglomerationsCollection:
      type: object
      required:
        - data
        - links
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Agglomeration/properties/data'
        links:
          $ref: '#/components/schemas/PaginationData'
    PaginationData:
      type: object
      required:
        - self
      properties:
        self:
          type: string
          format: uri
          description: link to the current page
        first:
          type: string
          format: uri
          description: link to the first page
        last:
          type: string
          format: uri
          description: link to the last page
        prev:
          type: string
          format: uri
          description: link to the previous page
        next:
          type: string
          format: uri
          description: link to the next page
