openapi: 3.1.1
info:
  title: NetBill organizations-svc API
  description: API documentation for organizations-svc
  version: 0.1.0

servers:
  - url: http://localhost:8003

paths:
  /organizations-svc/v1/organizations/:
    $ref: './spec/paths/Organizations.yaml'

  /organizations-svc/v1/organizations/{organization_id}:
    $ref: './spec/paths/Organization.yaml'
  /organizations-svc/v1/organizations/{organization_id}/media/upload/url:
    $ref: './spec/paths/CreateOrganizationUploadMediaLink.yaml'
  /organizations-svc/v1/organizations/{organization_id}/media/upload/icon:
    $ref: './spec/paths/DeleteOrganizationUploadIcon.yaml'
  /organizations-svc/v1/organizations/{organization_id}/media/upload/banner:
    $ref: './spec/paths/DeleteOrganizationUploadBanner.yaml'
  /organizations-svc/v1/organizations/{organization_id}/activate:
    $ref: './spec/paths/ActivateOrganization.yaml'
  /organizations-svc/v1/organizations/{organization_id}/deactivate:
    $ref: './spec/paths/DeactivateOrganization.yaml'
  /organizations-svc/v1/organizations/{organization_id}/suspend:
    $ref: './spec/paths/SuspendOrganization.yaml'
  /organizations-svc/v1/organizations/{organization_id}/unsuspend:
    $ref: './spec/paths/UnsuspendOrganization.yaml'
  /organizations-svc/v1/organizations/{organization_id}/invites:
    $ref: './spec/paths/OrganizationInvites.yaml'
  /organizations-svc/v1/organizations/{organization_id}/leave:
    $ref: './spec/paths/LeaveOrganization.yaml'

  /organizations-svc/v1/members/:
    $ref: './spec/paths/Members.yaml'
  /organizations-svc/v1/members/{member_id}:
    $ref: './spec/paths/Member.yaml'

  /organizations-svc/v1/invites/:
    $ref: './spec/paths/CreateInvite.yaml'
  /organizations-svc/v1/invites/me:
    $ref: './spec/paths/MyInvites.yaml'
  /organizations-svc/v1/invites/{invite_id}:
    $ref: './spec/paths/GetInvite.yaml'
  /organizations-svc/v1/invites/{invite_id}/accept:
    $ref: './spec/paths/AcceptInvite.yaml'
  /organizations-svc/v1/invites/{invite_id}/decline:
    $ref: './spec/paths/DeclineInvite.yaml'
  /organizations-svc/v1/invites/{invite_id}/cancelled:
    $ref: './spec/paths/CancelledInvite.yaml'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    # requests
    CreateOrganization:
      $ref: './spec/components/schemas/requests/CreateOrganization.yaml'
    UpdateOrganization:
      $ref: './spec/components/schemas/requests/UpdateOrganization.yaml'
    UpdateMember:
      $ref: './spec/components/schemas/requests/UpdateMember.yaml'
    CreateInvite:
      $ref: './spec/components/schemas/requests/CreateInvite.yaml'
    DeleteUploadOrgIcon:
      $ref: './spec/components/schemas/requests/DeleteUploadOrgIcon.yaml'
    DeleteUploadOrgBanner:
      $ref: './spec/components/schemas/requests/DeleteUploadOrgBanner.yaml'

    # responses
    PaginationData:
      $ref: './spec/components/schemas/responses/PaginationData.yaml'
    UploadOrgMediaLinks:
      $ref: './spec/components/schemas/responses/UploadOrgMediaLinks.yaml'
    UploadResourcesLink:
      $ref: './spec/components/schemas/responses/UploadResourcesLink.yaml'

    ProfileData:
      $ref: './spec/components/schemas/responses/ProfileData.yaml'
    ProfileAttributes:
      $ref: './spec/components/schemas/responses/ProfileAttributes.yaml'

    Organization:
      $ref: './spec/components/schemas/responses/Organization.yaml'
    OrganizationData:
      $ref: './spec/components/schemas/responses/OrganizationData.yaml'
    OrganizationsCollection:
      $ref: './spec/components/schemas/responses/OrganizationsCollection.yaml'

    Member:
      $ref: './spec/components/schemas/responses/Member.yaml'
    MembersCollection:
      $ref: './spec/components/schemas/responses/MembersCollection.yaml'
    MemberIncluded:
      $ref: './spec/components/schemas/responses/MemberIncluded.yaml'

    Invite:
      $ref: './spec/components/schemas/responses/Invite.yaml'
    InvitesCollection:
      $ref: './spec/components/schemas/responses/InvitesCollection.yaml'
    InviteIncluded:
      $ref: './spec/components/schemas/responses/InviteIncluded.yaml'

    Errors:
      $ref: './spec/components/schemas/responses/Errors.yaml'