openapi: 3.1.0
info:
  title: organizations-svc API
  description: API documentation for organizations-svc
  version: 0.1.0

paths:
  /test:
    post:
      tags:
        - Test
      description: Test
      responses:
        '201':
          description: successfully

components:
  schemas:
    # requestBodies:
    CreateOrganization:
      $ref: './spec/components/schemas/CreateOrganization.yaml'
    UpdateOrganization:
      $ref: './spec/components/schemas/UpdateOrganization.yaml'
    UpdateMember:
      $ref: './spec/components/schemas/UpdateMember.yaml'
    SentInvite:
      $ref: './spec/components/schemas/SentInvite.yaml'
    CreateRole:
      $ref: './spec/components/schemas/CreateRole.yaml'
    UpdateRole:
      $ref: './spec/components/schemas/UpdateRole.yaml'
    UpdateRolesRanks:
      $ref: './spec/components/schemas/UpdateRolesRanks.yaml'
    UpdateRolePermissions:
      $ref: './spec/components/schemas/UpdateRolePermissions.yaml'

    # responses:
    PaginationData:
      $ref: './spec/components/schemas/PaginationData.yaml'

    Organization:
      $ref: './spec/components/schemas/Organization.yaml'
    OrganizationsCollection:
      $ref: './spec/components/schemas/OrganizationsCollection.yaml'

    Member:
      $ref: './spec/components/schemas/Member.yaml'
    MemberCollection:
      $ref: './spec/components/schemas/MemberCollection.yaml'

    Invite:
      $ref: './spec/components/schemas/Invite.yaml'
    InvitesCollection:
      $ref: './spec/components/schemas/InvitesCollection.yaml'

    Role:
      $ref: './spec/components/schemas/Role.yaml'
    RolesCollection:
      $ref: './spec/components/schemas/RolesCollection.yaml'
    RolePermissions:
      $ref: './spec/components/schemas/RolePermissions.yaml'
