openapi: 3.1.1
info:
  title: organizations-svc API
  description: API documentation for organizations-svc
  version: 0.1.0

paths:
  /test:
    post:
      tags:
        - Test
      description: Test
      responses:
        '201':
          description: successfully

components:
  schemas:
    # requestBodies:
    CreateOrganization:
      $ref: './spec/components/schemas/requests/CreateOrganization.yaml'
    UpdateOrganization:
      $ref: './spec/components/schemas/requests/UpdateOrganization.yaml'
    UpdateMember:
      $ref: './spec/components/schemas/requests/UpdateMember.yaml'
    CreateInvite:
      $ref: './spec/components/schemas/requests/CreateInvite.yaml'
    DeleteUploadOrgIcon:
      $ref: './spec/components/schemas/requests/DeleteUploadOrgIcon.yaml'
    DeleteUploadOrgBanner:
      $ref: './spec/components/schemas/requests/DeleteUploadOrgBanner.yaml'

    # responses:
    PaginationData:
      $ref: './spec/components/schemas/responses/PaginationData.yaml'
    UploadResourcesLink:
      $ref: './spec/components/schemas/responses/UploadResourcesLink.yaml'

    ProfileData:
      $ref: './spec/components/schemas/responses/ProfileData.yaml'
    ProfileAttributes:
      $ref: './spec/components/schemas/responses/ProfileAttributes.yaml'

    Organization:
      $ref: './spec/components/schemas/responses/Organization.yaml'
    OrganizationData:
      $ref: './spec/components/schemas/responses/OrganizationData.yaml'
    OrganizationsCollection:
      $ref: './spec/components/schemas/responses/OrganizationsCollection.yaml'
    UploadOrgMediaLinks:
      $ref: './spec/components/schemas/responses/UploadOrgMediaLinks.yaml'

    Member:
      $ref: './spec/components/schemas/responses/Member.yaml'
    MemberCollection:
      $ref: './spec/components/schemas/responses/MemberCollection.yaml'
    MemberIncluded:
      $ref: './spec/components/schemas/responses/MemberIncluded.yaml'

    Invite:
      $ref: './spec/components/schemas/responses/Invite.yaml'
    InvitesCollection:
      $ref: './spec/components/schemas/responses/InvitesCollection.yaml'
    InviteIncluded:
      $ref: './spec/components/schemas/responses/InviteIncluded.yaml'
