openapi: 3.1.0
info:
  title: cities-svc API
  description: API documentation for cities-svc
  version: 0.1.0

paths:
  /test:
    post:
      tags:
        - Test
      description: Test
      responses:
        '201':
          description: successfully

components:
  schemas:
    # requestBodies:
    CreateAgglomeration:
      $ref: './spec/components/schemas/CreateAgglomeration.yaml'
    UpdateAgglomeration:
      $ref: './spec/components/schemas/UpdateAgglomeration.yaml'

    # responses:
    Agglomeration:
      $ref: './spec/components/schemas/Agglomeration.yaml'
    AgglomerationsCollection:
      $ref: './spec/components/schemas/AgglomerationsCollection.yaml'
    PaginationData:
      $ref: './spec/components/schemas/PaginationData.yaml'
